### ISSUE TITLE
Bug: Alt/else clause is ignored

### ISSUE THREAD

**Issue by HaaLeo** [plantuml/plantuml-server#100]
# Bug Report
When creating a diagram with an `alt/else` clause the preview and the exported picture do not contain that clause. I checked for the `jetty` and `tomcat` server, trying both in a docker container.

## Steps to reproduce
1. Get docker image: `docker pull plantuml/plantuml-server:tomcat`
1. Start server `docker run -d -p 8080:8080 plantuml/plantuml-server:tomcat`
1. In your browser go to `localhost:8080`
1. Paste in the following:
    ```
    @startuml
    alt Hello
        ML -> DB: Update Cache
    else
        ML -> ML:
    @enduml
    ```
1. Send it to the server

## Expected behavior
A diagram containing an `alt/else` group

## Actual behavior
A diagram like this without the group:
![hello](https://user-images.githubusercontent.com/23164374/57210412-df382e00-6fdc-11e9-9f2a-bf799ab51faf.png)

**Comment by arnaudroques** [comment]
Thanks for the feedback.
However, there is a "end" missing.
See http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuKhCAL7mICt9oUTI009V7mLTEmKN9ok5q8AKn99K1UV4v8nKhjISubI4F92quahDI-5o0190Cm00

**Comment by HaaLeo** [comment]
😅 🙄 perfect Thanks
