### ISSUE TITLE
Decision node in loop

### ISSUE THREAD

**Issue by JirkaDellOro** [plantuml/plantuml-server#101]
In an activity diagram, the while statement in plantuml creates a decision node with six corners, even when it contains no text. It would be great, if in this case it looks like a regular decision node, with only four corners. This would then comply with the UML standard.

**Comment by arnaudroques** [comment]
Thanks for the idea.
This is fixed in last beta http://beta.plantuml.net/plantuml.jar

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @JirkaDellOro for the report.
- Thanks PlantUML team for your work.

✔️ This issue can be closed.
Regards.
