### ISSUE TITLE
Subactivities and fork-symbol

### ISSUE THREAD

**Issue by JirkaDellOro** [plantuml/plantuml-server#102]
It would be great to have the possibility, to group parts of an activity diagram as a sub-activity, which is then rendered in a rectangle with rounded corners. At this point of time, I'm using the "package" keyword for this, but looks improper there and doesn't comply to the standards.

In the calling action, we then need the trident-symbol, in order to mark that the activity invoked is rendered someplace else.

**Comment by arnaudroques** [comment]
Could you post a simple image of what you are expecting ? It will help us to understand the request.
Thanks

**Comment by JirkaDellOro** [comment]
Sure. Please take a look at "4. Subactivities" in this document
https://github.com/JirkaDellOro/EIA2/blob/master/ActivityDia2Code.pdf

**Comment by JirkaDellOro** [comment]
In English, the symbol I refer to may be called "trident"

**Comment by HeinrichAD** [comment]
Even if there may not be a ready-made solution, this can be achieved fairly easily with [sprites](https://plantuml.com/sprite).

Note: Sprites are scalable: `<$trident{scale=2}>` or `<$trident*2>`

### Example 1
```plantuml
@startuml
sprite $trident {
  000000F000000
  000000F000000
  000000F000000
  000000F000000
  000000F000000
  FFFFFFFFFFFFF
  F00000F00000F
  F00000F00000F
  F00000F00000F
  F00000F00000F
  F00000F00000F
}

(*) --> "greet\t<$trident>" as greet
greet --> (*)
@enduml
```

Result:

![image](https://github.com/plantuml/plantuml-server/assets/5962361/988dd2a0-94b1-491a-b0b0-912536f03917)


### Example 2
Using SVG Images.

```plantuml
@startuml
sprite trident <svg width="8" height="8"><path d="M3.5 0h1v3.5H8V8H7V4.5H4.5V8h-1V4.5H1V8H0V3.5h3.5z"/></svg>

(*) --> "greet    <$trident>" as greet
greet --> (*)
@enduml
```

Note:  There is a limited support for SVG images.

Result:

![image](https://github.com/plantuml/plantuml-server/assets/5962361/b818a2df-4471-42bd-9851-5a09d434ce40)
