### ISSUE TITLE
"@startwbs" feature not available in docker server(tomcat)

### ISSUE THREAD

**Issue by pyo0723** [plantuml/plantuml-server#107]
Hi, 

I encounter an error when trying to draw @startuml diagrams even with the demo diagram code available on plantuml site.

<pre>
```plantuml
@startwbs
* Business Process Modelling WBS
** Launch the project
*** Complete Stakeholder Research
*** Initial Implementation Plan
** Design phase
*** Model of AsIs Processes Completed
**** Model of AsIs Processes Completed1
**** Model of AsIs Processes Completed2
*** Measure AsIs performance metrics
*** Identify Quick Wins
** Complete innovate phase
@endwbs
```
</pre>

The figure below is displayed and the uml diagram is not displayed.
![image](https://user-images.githubusercontent.com/30519564/58241022-1cdfd980-7d87-11e9-83e7-ff33220f6396.png)

<br/>

Clicking on the image will take you to a page with the message below.
![image](https://user-images.githubusercontent.com/30519564/58241330-b60ef000-7d87-11e9-9f48-58cb47b9e4e2.png)

---
- another sample

<pre>
```plantuml
* Business Process Modelling WBS
** Launch the project
*** Complete Stakeholder Research
*** Initial Implementation Plan
** Design phase
*** Model of AsIs Processes Completed
****< Model of AsIs Processes Completed1
****> Model of AsIs Processes Completed2
***< Measure AsIs performance metrics
***< Identify Quick Wins
```
</pre>

The figure below is displayed and the uml diagram is not displayed.
![image](https://user-images.githubusercontent.com/30519564/58242481-dcce2600-7d89-11e9-9655-194c1812e3f3.png)

I use the latest image from docker hub.
> $ docker run -d -p 8080:8080 plantuml/plantuml-server:tomcat

How can I use @startwbs? 

Is it working properly, Or is @startwbs not working yet?

**Comment by arnaudroques** [comment]
It should work.

Could you check the PlantUML version :
```plantuml
version
```

You seems to use PlantUML with another tool. Which one is it ? It's possible that the issue comes from this other tools that does not support @startwbs

**Comment by leejongpyo** [comment]
We use the gitlab ce docker. I use a planuml on our gitlab. 
Does not Gitlab support @startwbs??

**Comment by pyo0723** [comment]
We don't use any wiki. I have registered a plantuml diagram with the issue provided by gitlab. Or we use the wiki from gitlab's menu.
And I checked on  http://myserver:8090/plantuml/uml.  
I still get an error.

![image](https://user-images.githubusercontent.com/30519564/58300640-5a437600-7e1e-11e9-8617-86a91474f52c.png)

**Comment by arnaudroques** [comment]
Could you try;
```
@startuml
version
@enduml
```
To check your exact version.
Thanks

**Comment by pyo0723** [comment]
I Checked version. 

![image](https://user-images.githubusercontent.com/30519564/58685480-dc9bdf00-83b6-11e9-911a-a3ace1e508eb.png)

**Comment by arnaudroques** [comment]
That's strange : this version is not up to date. The last one is 1.2019.6
I'm not sure if there is an issue with docker. Any idea anyone ?

**Comment by pyo0723** [comment]
Thank you for your reply. I did update plantuml docker image and I confirm the correct work result. 
Thanks you. 

![image](https://user-images.githubusercontent.com/30519564/58783642-60a2d080-861c-11e9-99ef-8c5234b48ce4.png)

<br/><br/>




![image](https://user-images.githubusercontent.com/30519564/58783577-34874f80-861c-11e9-944d-e69e151ff6db.png)
