### ISSUE TITLE
feature-request: Ability to disable/hide stateful functionality

### ISSUE THREAD

**Issue by ghuser** [plantuml/plantuml-server#108]
We are installing plantuml-server just to use the proxy feature, so that users reference plantuml diagrams which they have already committed to some repository. 

We don't want to support any storage of diagrams on the service-side.

So we would like to be able to disable the stateful features, so that users do not accidentally start creating plantuml diagrams on the server (which can be lost in the future).

e.g. adding support for `PLANTUML_STATELESS_ONLY=on` or `PLANTUML_ENABLED_FEATURES=proxy,someotherfeature` could be an option.

**Comment by arnaudroques** [comment]
> We don't want to support any storage of diagrams on the service-side.
> So we would like to be able to disable the stateful features

I'm confused about your question : the plantuml-server (as the online server) is completely stateless (see http://plantuml.com/faq ).
So there are no stateful feature.

Thanks to clarify your request!

**Comment by ghuser** [comment]
Great! 

I didn't test with long plantuml content, so I thought that the string might be some kind of hash.
I should have read the documentation more thoroughly. 

Thanx!
