### ISSUE TITLE
Proxy not enabled in Docker

### ISSUE THREAD

**Issue by pixie79** [plantuml/plantuml-server#109]
Hi,

When running the official docker container it appears the /plantuml/proxy endpoint is not enabled.

Can you please explain how to enable it as it is required for use when trying to follow the github markdown pattern but with offline code stores.

e.g

http://test.lodev.xyz:8081/plantuml/proxy?idx=0src=http://192.168.86.250:4567/documentation/architectural/images/test.puml

This is a loopback to my local running docker container, but i get a 404 on that url. Hitting just / i get the standard default running server ok.

Thanks

Mark

**Comment by alisabzevari** [comment]
I have the same problem. Maybe the docker image in docker is not up-to-date?

**Comment by dom54** [comment]
It is enabled on latest docker, but its not intuitive (to me). The proxy URL is the root context i.e. /proxy     not /plantuml/proxy or /uml/proxy

**Comment by mihaigalos** [comment]
@dom54 : how exactly did you get it running?
I tried pointing my firefox to `http://localhost:8080/proxy?src=https://raw.githubusercontent.com/mihaigalos/osi_stack/master/graphics/sources/session_handshake.puml`, no luck.

I'm hosting the server with `docker run -d --name plantuml -p 8080:8080 plantuml/plantuml-server:tomcat`.

**Comment by mihaigalos** [comment]
Up: I've got it running. 
Turns out everything was correct, I've had my browser filter requests to `github.com`  for whatever reason.
Hosting the file locally worked.

For internet hosted diagrams, I'm using the endpoint `http://www.plantuml.com/plantuml/proxy?cache=no&src=myserver.com&source.puml` as described [here](https://stackoverflow.com/a/32771815/2394327).

**Comment by mihaigalos** [comment]
Up2: for corporate self-hosted GitHub, one may create a GitHub token and use the following syntax when firing up the docker.
This effectively allows reaching the raw *.puml from inside the docker via proxy upon such a request.

```bash
 docker run -d --rm -p 8081:8080 --env "HTTP_AUTHORIZATION=token abcdef" plantuml/plantuml-server:tomcat
```

**Comment by ekaterina-poslavskaya** [comment]
Hi!
I wanted to publish some documentation based on plantuml files from my local Gitlab repository. Gitlab and Plantuml server are offline. 
So, I have 2 servers: gitlab server and another one for plantuml server app. After installing plantuml server in docker container, I've configured gitlab and plantuml-server as it described in gitlab docs. So, simple diagrams were generating in my gitlab wiki. But my goal was to generate diagrams from files in repository, not from plain markdown.

And there were some errors with proxy:
1. in gitlab wiki for this text:
```plantuml
@startuml
!include https://gitlab.lan/poslavskaya/archi/-/raw/wiki+plantuml/t.puml
@enduml
```
I've got the PlantUML error: Unable to open URL

2. in browser for this url:
http://plantumlserver.lan:9075/proxy?cache=no&src=https://gitlab.lan/poslavskaya/archi/-/raw/wiki+plantuml/t.puml

I've got Status code 500: Exception: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0

In docker logs there was java error: unable to find valid certification path to requested target

So:
1. I've exported the gitlab certificate
2. Copied it into the plantuml server  container
sudo docker cp /home/poslavskaya/Downloads/gitlab.lan 7a05e004h3j6:/home/gitlab.lan
3. Got into the docker container with root grants
sudo docker container exec -it -u root plantuml bash
4. Installed the cert 
keytool -import -trustcacerts -cacerts -storepass changeit -alias gitlab -file /home/gitlab.lan
5. Restarted the docker container

After this gitlab wiki successfully generated diagram from file in repository, but url with plantuml/proxy (http://plantumlserver.lan:9075/proxy?cache=no&src=...) still unaccessible.

**Comment by HeinrichAD** [comment]
PlantUML Server does not only have one proxy, but two.

Let's assume your PlantUML Server instance runs with the base URL \<<http://localhost:8080/plantuml>> and you want to render the diagram from \<<http://localhost:8080/plantuml/proxy/https://raw.githubusercontent.com/plantuml/plantuml-server/master/src/main/webapp/resource/test/test2diagrams.txt>>.

The proxy has the following structure:
- `/proxy`

And takes the 3 arguments: `src`, `idx` and `fmt`.

Therefore, you can achieve this e.g. in the following ways:
<http://localhost:8080/plantuml/proxy?src=https://raw.githubusercontent.com/plantuml/plantuml-server/master/src/main/webapp/resource/test/test2diagrams.txt>

The **_old proxy_** has the following structure(s):
- `/proxy/{url}`
- `/proxy/{index}/{url}`
- `/proxy/{format}/{url}`

### Documentation

Unfortunately, I could not found any official PlantUML Server API documentation.

That's the reason why I started to create my own OpenAPI Specification. In the following you will find the Proxy and old Proxy part. (No guarantee of completeness and correctness.)

<details><summary>Partial OpenAPI Documentation (not official)</summary>

```yaml
openapi: 3.0.1

info:
  title: PlantUML Server
  version: ${{plantuml-version}}
  description: |
    PlantUML Server is a web application to generate UML diagrams on-the-fly.

    To know more about PlantUML, please visit [https://plantuml.com](https://plantuml.com).
  license:
    name: GPL-3.0
    url: https://github.com/plantuml/plantuml-server/blob/master/COPYING

servers:
  - url: ${{contextpath}}
    description: PlantUML Server

tags:
  - name: Proxy  # + Old Proxy
    description: Retrieves the diagram source of a web resource (web html page) and renders it.


paths:
  ## Proxy ####################################################################
  /proxy:
    get:
      tags:
        - Proxy
      parameters:
        - name: src
          in: query
          description: PlantUML diagram source URL
          required: true
          schema:
            type: string
        - name: idx
          in: query
          description: PlantUML diagram page index number (starting with `0`)
          required: false
          schema:
            type: number
        - name: fmt
          in: query
          description: PlantUML diagram format
          required: false
          schema:
            $ref: '#/components/schemas/DiagramType'
      responses:
        '200':
          description: Successful operation
  ## Old proxy ##################################
  /proxy/{url}:
    get:
      deprecated: true
      tags:
        - Proxy
      parameters:
        - name: url
          in: path
          description: PlantUML diagram source URL
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
  /proxy/{index}/{url}:
    get:
      deprecated: true
      tags:
        - Proxy
      parameters:
        - name: index
          in: path
          description: PlantUML diagram page index number (starting with `0`)
          required: true
          schema:
            type: number
        - name: url
          in: path
          description: PlantUML diagram source URL
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
  /proxy/{format}/{url}:
    get:
      deprecated: true
      tags:
        - Proxy
      parameters:
        - name: format
          in: path
          description: PlantUML diagram format
          required: true
          schema:
            $ref: '#/components/schemas/DiagramType'
        - name: url
          in: path
          description: PlantUML diagram source URL
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
  /proxy/{index}/{format}/{url}:
    get:
      deprecated: true
      tags:
        - Proxy
      parameters:
        - name: index
          in: path
          description: PlantUML diagram page index number (starting with `0`)
          required: true
          schema:
            type: number
        - name: format
          in: path
          description: PlantUML diagram format
          required: true
          schema:
            $ref: '#/components/schemas/DiagramType'
        - name: url
          in: path
          description: PlantUML diagram source URL
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation

components:
  schemas:
    DiagramType:
      type: string
      enum:
        - png
        - svg
        - txt
        - pdf
        - base64
        - eps
        - epstext
        - map
```

</details>
