### ISSUE TITLE
Language endpoint not working on HTTPS version of plantuml.com

### ISSUE THREAD

**Issue by skuro** [plantuml/plantuml-server#112]
@arnaudroques while debugging a [`plantuml-mode` issue](https://github.com/skuro/plantuml-mode/issues/101) I discovered that the following URL stopped working (note the HTTPS protocol):

https://www.plantuml.com/plantuml/language

While it used to work in the past, now it triggers a redirect to http://plantuml.com. Accessing the same URL on the HTTP (non-encrypted) protocol still works, but that's obviously not secure.
I saw that rendering URLs of the online PlantUML server are actually accessible, would it be possible for you to re-enable the secure URL for the language spec endpoint?

_Originally posted by @skuro in https://github.com/plantuml/plantuml-server/pull/106#issuecomment-519820981_

**Comment by arnaudroques** [comment]
Thanks for the feedback.
This should be ok now.
(note that you might have browser cache issue)

**Comment by skuro** [comment]
Works like a charm once again, thank you so much for the fast support!
