### ISSUE TITLE
Please add versioning and version tags for your plantuml docker hub image.

### ISSUE THREAD

**Issue by zangrum** [plantuml/plantuml-server#114]
I am attempting to bring your docker image into an internal company artifactory and the lack of versioning causes compliance and usage issues.  There are many guides,  These two looked good.  
https://www.techrepublic.com/article/how-to-use-docker-tags-to-add-version-control-to-images/
https://medium.com/better-programming/how-to-version-your-docker-images-1d5c577ebf54

Thanks

**Comment by arnaudroques** [comment]
I have very limited knowledge about docker.
If you could provide some merge request, this would be great :-)

Regards,
Arnaud

**Comment by jarv** [comment]
@arnaudroques submitted https://github.com/plantuml/plantuml-server/pull/115

**Comment by jarv** [comment]
With v1.2019.11 there are tags now so I think this can be closed https://hub.docker.com/r/plantuml/plantuml-server/tags?page=1&name=v1.2019.11
