### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by sasahoo** [plantuml/plantuml-server#121]
Hi,

I have setup the standalone server. When I submit the puml file, the browser becomes blank. I don't understand why. Can we check any logs generated to look into this issue?  

Regards,
Sandip

**Comment by HeinrichAD** [comment]
For documentation purpose:

1. `mvn jetty:run`  
  The logs will directly display inside the terminal.
2. `docker run -d -p 8080:8080 -e BASE_URL=plantuml plantuml/plantuml-server`
  If you run your docker container detached and you didn't name your container, you can see the logs over the container ID (see `docker ps`) with the following command: `docker logs <container-id>`. Add the `-f` flag if you want to continue seeing the incoming logs.
3. Web Browser Logging  
  Naturally, you can check what the web browser tells you. E.g. what kind of response the server send etc.  
  Most web browsers open their "Developer Tools" with <kbd>F12</kbd>.  
  Alternativly, you could also use `curl -v ...`.

Also, a blank web browser after opening a website/submitting a form most likely occurs when the web browser does not receive a response from the server.
