### ISSUE TITLE
new server release for v1.2019.12

### ISSUE THREAD

**Issue by jarv** [plantuml/plantuml-server#124]
@arnaudroques would it be possible to get a new server release for v1.2019.12 so there are official tagged docker images? We would like to get a new tagged release that contains the security fix for https://github.com/plantuml/plantuml-server/issues/122

**Comment by arnaudroques** [comment]
Well, release v1.2019.12 has been tagged here
https://github.com/plantuml/plantuml-server/releases/tag/v1.2019.12
Any issue on docker ?

**Comment by jarv** [comment]
Weird, I see the tag and the commit https://github.com/plantuml/plantuml-server/commit/37a96a29c450af6b1fa75ac81a789edf761bf995 but it is not on master https://github.com/plantuml/plantuml-server/blob/master/pom.xml#L182

**Comment by jarv** [comment]
maybe there was a force-push on master?

**Comment by jarv** [comment]
@arnaudroques maybe we should create a new commit that bumps the version on master and re-tag?

**Comment by arnaudroques** [comment]
@jarv I've just created a dummy version https://github.com/plantuml/plantuml-server/releases/tag/v1.2019.12b
But I'm not sure it will solve the issue...

**Comment by cep21** [comment]
Any docker image for v1.2020.1?  Is this created by CI or by hand?

**Comment by arnaudroques** [comment]
We've just committed v1.2020.2. It should be created by CI.
Maybe we need some help here...

**Comment by jarv** [comment]
@arnaudroques The tags stopped working with 

https://github.com/plantuml/plantuml-server/commit/b98e227ce7a19c6472039f4500473569f7211147

Because a condition was added for both tag=true and branch=master. tags are not associated with branches so this was never evaluating to true. I fixed this and cleaned up the travis configuration in

https://github.com/plantuml/plantuml-server/pull/139

**Comment by jarv** [comment]
This is now resolved
