### ISSUE TITLE
Allow http urls in plantuml.include.path

### ISSUE THREAD

**Issue by bharatrajagopalan** [plantuml/plantuml-server#129]
@arnaudroques 

As discussed in the thread https://github.com/plantuml/plantuml-server/issues/122

Can plantuml.include.path  be designed to either accept an url or a file or both?

e.g. if i want to include files from a url i have to currently specify as below
!include http://domain:port/path1/path2/file1
!include http://domain:port/path1/path3/file2

instead if i could just specify
plantuml.include.path="http://domain:port/path1"
!include path2/file1
include path3/file2

Currently i can do (with ALLOW_PLANTUML_INCLUDE=true)
plantuml.include.path=/path-to/path1

!include path2/file1
!include path3/file2

So being able to specify url or file path or both in plantuml.include.path (e.g. plantuml.include.path="/path-to/path1,http://domain:port/path1/") this will basically maximise flexibility without needing to change  puml files  irrespective of the whether i use jar or server

**Comment by HeinrichAD** [comment]
For documentation purpose:

There exists a documentation on how to [Deploy PlantUML safely](https://plantuml.com/security).

In the subsection _Allowlists_ are currently three different variables lists which allows to define allowlists:
- `plantuml.allowlist.path` for local files
- `plantuml.include.path` for local files
- `plantuml.allowlist.url` for remote resources (URL)

To _allow_ URLs you can use the `plantuml.allowlist.url` allowlists variable.

----

Also please take a note of the following hint (which is currently stated inside the README):

> **Breaking changes**:  
> The PlantUML core removed the deprecated `ALLOW_PLANTUML_INCLUDE` environment property feature and switch to the
> `PLANTUML_SECURITY_PROFILE` concept with version `v1.2023.9`.
> All details about PlantUML's security can be found on <https://plantuml.com/security>.
>
> By default PlantUML server sets the `PLANTUML_SECURITY_PROFILE` to `INTERNET`.
> If you need more access to e.g. other ports than 80 (http) and 443 (https) or even access to local files, please
> consider using one of the allowlist features.
> It is strongly advised **not** to set the `PLANTUML_SECURITY_PROFILE` below `INTERNET`!

**Comment by bharatrajagopalan** [comment]
Thanks that clarifies!
