### ISSUE TITLE
Enable PDF export

### ISSUE THREAD

**Issue by blueogive** [plantuml/plantuml-server#130]
I attempted to build a Docker image based on a WAR equipped to export PDF file. My attempt can be inspected on this [branch](https://github.com/blueogive/plantuml-server/tree/pdf_support). I am unfamiliar with Java build tooling, but following the guidance in issue #116, I added the dependencies for PDF export identified in the [documentation](https://plantuml.com/pdf) to the pom.xml file. I wound up with a Docker image that builds successfully and generates eps/png/svg output, but returns '404 Not Found' in response to a request for pdf output.

Where did I go wrong?

**Comment by tphani** [comment]
PDF support is not there in web-application. The error '404 not found' has nothing to do with your changes. It is coming due to no mapping defined for the pattern "/pdf" in web.xml

**Comment by blueogive** [comment]
Thank you for the reply. I've not worked with Java web applications. Are you saying it is not possible to configure the application to return pdf responses in the same manner it will return svg responses?

I modified the `web.xml` file to include a servlet mapping block:
```xml
	<servlet-mapping>
		<servlet-name>pdfservlet</servlet-name>
		<url-pattern>/pdf/*</url-pattern>
	</servlet-mapping>
```

And realized that I don't know what file contains the correct class for the servlet configuration:
```xml
	<servlet>
		<servlet-name>pdfservlet</servlet-name>
		<servlet-class>net.sourceforge.plantuml.ant.PlantUmlTask</servlet-class>
	</servlet>
```
This does not work.

**Comment by tphani** [comment]
Exactly, you could not find right class for defining the mapping for pdf as it does not exist. The logic to convert svg to pdf is added in standalone code base only. We need to get that logic into web application code and probably expose it through another servlet similar to SvgServlet.
