### ISSUE TITLE
Cannot insert from google docs add-on

### ISSUE THREAD

**Issue by jianfeiliao** [plantuml/plantuml-server#131]
I followed the instructions from https://sites.google.com/site/plantumlgizmo/learn#TOC-Can-I-specify-a-different-PlantUML-server-on-a-private-network- and run my plantuml-server (jetty version) locally using docker, it validates fine, but it's still giving me this error when I tried to insert the image thru the google docs add-on:

```
The insert operation could not be performed.
Unable to transfer image as "data:..." URL. See this FAQ
```

Is there more I need to configure to enable that?

**Comment by fuhrmanator** [comment]
I'm the dev of the PlantUMLGizmo - I just found this issue. I have not tried that feature in a long time. Did you resolve it?

**Comment by jianfeiliao** [comment]
i have not resolved this but i also no longer use this software now, feel free to close this.
