### ISSUE TITLE
Auto Include

### ISSUE THREAD

**Issue by stnguyen90** [plantuml/plantuml-server#132]
Is it possible to auto include skinparams with a custom docker image?

**Comment by imochoa** [comment]
I'm pretty sure you could. I did something similar like a year ago here:
https://github.com/miy4/docker-plantuml/pull/5

I still haven't gotten around to addressing the issues there and finishing it, but the main idea is pretty simple:
- put your skinparams config file in the image somewhere `/config/my_style.iuml`
- in the plantuml call, use the `-I` flag to include them `java -jar /app/plantuml.jar -I/config/*.iuml`

Sorry for referencing another plantuml repo here, but I though there was enough overlap in this case to justify it :)

**Comment by stnguyen90** [comment]
That definitely makes sense for the plantuml jar, but I couldn't find the right option to pass the config to a plantuml server. Is it the same?

**Comment by HeinrichAD** [comment]
For documentation purpose:

It is possible to use the `PLANTUML_CONFIG_FILE` environment variable to automatically include e.g. skinparams. To be precise, the file content will be added before each PlantUML diagram code.

----

Note: The current implementation does not support file path pattern. That means you can only include exactly one file.

https://github.com/plantuml/plantuml-server/blob/294b2a241829855455f6fea3dca03a7d49e9d262/src/main/java/net/sourceforge/plantuml/servlet/DiagramResponse.java#L138-L145
