### ISSUE TITLE
Jetty and tomcat generate different images from the same diagram

### ISSUE THREAD

**Issue by TheoLeCalvar** [plantuml/plantuml-server#138]
I noticed that some diagrams are rendered differently if you use the tomcat or the jetty image.

For instance, this diagram:
```
@startuml
'skinparam monochrome true
		state "PubliphoneV6" as PubliphoneV6 {
		    Raccroché : entry/couperCom()
			state "Raccroché" as Raccroché  {
			}
			state "Décroché" as Décroché  {
				state Décroché_choice <<choice>>
				Décroché_FinCom : entry/finComUser()
				state "FinCom" as Décroché_FinCom  {
				}
				state "AttentePièce" as Décroché_AttentePièce  {
				}
				state "AttenteNuméro" as Décroché_AttenteNuméro  {
				}
				state "AttenteDécrochage" as Décroché_AttenteDécrochage  {
				}
				state "EnCommunication" as Décroché_EnCommunication  {
				}
				
				[*] --> Décroché_AttentePièce 
				Décroché_AttentePièce --> Décroché_choice : when(Credit>=2€)/ret = initCom()
				Décroché_choice --> Décroché_AttenteNuméro : [ret == OK]/activerHP
				Décroché_choice --> Décroché_FinCom : [else]
				Décroché_AttenteNuméro --> Décroché_AttenteDécrochage : composer(num)/acheminerNuméro(num)
				Décroché_AttenteDécrochage --> Décroché_EnCommunication : débuterCom/activerMicro()
				Décroché_AttenteNuméro --> Décroché_FinCom : erreurCom
				Décroché_AttenteDécrochage --> Décroché_FinCom : erreurCom
				Décroché_EnCommunication --> Décroché_FinCom : finComCorrespondant
				Décroché_EnCommunication --> Décroché_FinCom : when(credit <= 0)
			}

            [*] --> Raccroché 
            Raccroché --> Décroché : décrocher
            Décroché --> Raccroché : raccrocher
            Décroché --> Décroché[H] : mettrePièce(pièce)/Credit = incrémenterCrédit(pièce)
		}
@enduml
```

Tomcat renders it like [this](https://user-images.githubusercontent.com/1497742/79041385-bc03fe80-7bef-11ea-9992-be69a76fc202.png) and jetty like [that](https://user-images.githubusercontent.com/1497742/79041383-bad2d180-7bef-11ea-961b-1892dadbd92b.png).

I used the most recent `plantuml/plantuml-server:tomcat` and `plantuml/plantuml-server:jetty` docker images to generate these images.

Here is the version in the footer:
```
PlantUML Server 20200410-0728 / version 1202006
```

**Comment by arnaudroques** [comment]
Some wild guess: you don't have the same GraphViz version on both servers.
You can double check this with

```
@startuml
testdot
@enduml
```

**Comment by TheoLeCalvar** [comment]
You are right, tomcat and jetty images are not using the same version of GraphViz.

Tomcat: 2.38.0
Jetty: 2.40.1

I guess the difference in version is caused by the fact that the tomcat image used in the [Dockerfile.tomcat](https://github.com/plantuml/plantuml-server/blob/448c8f614fffb944c166ac71ccf737e6fac95329/Dockerfile.tomcat#L11) has not been updated for more than a year.
It looks like you should switch to `tomcat:9.0-jdk8-openjdk-slim`.

After updating Dockerfile.tomcat to use the newer base image both generate the same result.

Unfortunately it not the [good looking one](https://user-images.githubusercontent.com/1497742/79041383-bad2d180-7bef-11ea-961b-1892dadbd92b.png).

**Comment by arnaudroques** [comment]
Yes, unfortunately GraphViz 2.40.1 does not work well with PlantUML (see https://plantuml.com/faq )
The only way is to go back to 2.38.0. Sorry about that.

**Comment by TheoLeCalvar** [comment]
I understand. Thank you.
