### ISSUE TITLE
What is the "current working directory" of the server?

### ISSUE THREAD

**Issue by AjitDingankar** [plantuml/plantuml-server#143]
I'm new to PlantUML and using it in VSCode. I'm trying to run a local PlantUML server 
and getting "file not found" errors. 

I read the following excerpt about configuring the local server: 
```
ALLOW_PLANTUML_INCLUDE
Enables !include processing which can read files from the server into diagrams. Files are read relative to the current working directory.
```
I copied some puml files from the C4-PlantUML project (https://github.com/RicardoNiepel/C4-PlantUML) to the root folder of the PlantUML-Server repo. Then I restarted the jetty server with: 
`mvn jetty:run -D ALLOW_PLANTUML_INCLUDE=true`

However, I get the same errors to the effect of any of those puml files not being found. 

I couldn't find out anything about how to serve local files from the server. 
I'd appreciate it if you can point me to any information. 

Thanks, 
Ajit

**Comment by AjitDingankar** [comment]
I'm using absolute paths as a work-around, but would like to find a clean solution.

**Comment by saumyajyoti** [comment]
Below works for me. I can include *.puml filenames from include_dir.

set ALLOW_PLANTUML_INCLUDE=true 
set plantuml.include.path="C:/include_dir"
java -jar jetty-runner.jar plantuml.war

**Comment by HeinrichAD** [comment]
For documentation purpose:

Starting with `mvn jetty:run` the current working directory stays the same. That means if you run the command in `/tmp/plantuml` the working directory of the server will also be `/tmp/plantuml`.

Note: Please pay attation to the PlantUML Security settings: <https://plantuml.com/security>

Before version `v1.2023.9`: `ALLOW_PLANTUML_INCLUDE=true mvn jetty:run`
Starting with version `v1.2023.9`: `set plantuml.allowlist.path=$(pwd); mvn jetty:run`

For Docker you may find the following command useful: `docker run -it plantuml/plantuml-server pwd`
