### ISSUE TITLE
Preprocessor doesn't work on Docker

### ISSUE THREAD

**Issue by simongloor** [plantuml/plantuml-server#146]
##### Setup
 - I'm running the latest branch, last updated on the 05.05.2020, as a Docker container on my Synology NAS.
 - I've created a test file with all of the examples from https://plantuml.com/de/preprocessing and a simple diagram (A --> B) without any preprocessor functionality.

##### Problem 
 - Only the diagram without any preprocessor functionality works. 
 - All other images display "Syntax Error?" on the line I use the preprocessor functionality.

Let me know if I need to change anything on the setup or run more tests.  
You can also test the server directly [here](http://plantuml.pillars.ch:8088).

**Comment by arnaudroques** [comment]
This server is running PlantUML 1.2018.11 which is far too old (september 2018)
(see http://plantuml.pillars.ch:8088/uml/AqijAixCpmC0 )
I have no idea why it is not up to date.

**Comment by simongloor** [comment]
Awesome, thank you! I was able to update it and everything works fine now.

Apparently the tag 'plantuml/plantuml-server:tomcat' doesn't reflect the latest tomcat version as I would have expected.
