### ISSUE TITLE
dot files through proxy

### ISSUE THREAD

**Issue by ShahOdin** [plantuml/plantuml-server#149]
I am trying to render a dot file through `http://www.plantuml.com/plantuml/proxy?fmt=svg&src=path/to/dot/file` but I am having problem as it ignores it and shows alice and bob. 

But I can draw the dot diagram in the editor just fine.

Does this endpoint not support dot files as a url parameter?

**Comment by HeinrichAD** [comment]
For documentation purpose:

The proxy is only able to retrieve the diagram source of an _external_ web resource and renders it. This external web resource could have the name of dot file. E.g. `http://example.com/plantuml-files/.top-secret`.
All other data sources are not supported by the proxy. This includes local file resources.

A little bit more information about the proxy can be found here: https://github.com/plantuml/plantuml-server/issues/109#issuecomment-1627783415.
