### ISSUE TITLE
Use Recommended Version of Graphviz

### ISSUE THREAD

**Issue by SJrX** [plantuml/plantuml-server#150]
We noticed that some of the diagrams generated weirdly, and this post mentions that graphviz might be culprit.

https://forum.plantuml.net/11323/diagrams-on-docker-different-to-plantuml-com?show=11323#q11323

**Comment by eddiegroves** [comment]
Note sure if this is very easy, as currently it will get the *stable* version that Debian provides
https://packages.debian.org/search?suite=all&searchon=names&keywords=graphviz

**Comment by SJrX** [comment]
Maybe it's worth figuring out what upstream will do with graphviz if Linux distributions stop having the right version.

**Comment by Ludorg** [comment]
Hello,

I also noticed this strange behavior with the dot version.
Left to right on screenshots below are:
- local container with plantuml/plantuml-server:tomcat; 
- local container with plantuml/plantuml-server:latest ; 
- http://www.plantuml.com/plantuml/


![screen-1](https://user-images.githubusercontent.com/3078575/85179913-62205480-b282-11ea-9757-645842d99d4a.png)

![screen-2](https://user-images.githubusercontent.com/3078575/85179914-63518180-b282-11ea-820b-183b3e31cce3.png)

tomcat version is not affected as dot version is 2.38.0

Regards,

Ludovic

**Comment by stdoustderr** [comment]
I can only use the Jetty version because the Tomcat one needs to run as root.

What do we need to do to fix the version of Graphviz on Jetty here?

**Comment by SJrX** [comment]
It looks like finally graphviz 2.44 is compatible:

https://plantuml.com/faq
https://forum.plantuml.net/?qa=4531/possible-bug-with-relation-in-rectangle-screenshot

**Comment by stdoustderr** [comment]
How can we upgrade to 2.44 using the Jetty docker image?

I am happy to have a go my self and submit a PR but this a bit new for me so any pointers would help..

@SJrX

**Comment by SJrX** [comment]
I'm not a maintainer here, so I can't say what would be accepted. For us we just used an older version of the container. If you wanted a PR, with the thing I suggested, it would be change 

https://github.com/plantuml/plantuml-server/blob/master/Dockerfile.jetty

Figure out exactly what debian derivative they are using, and then finding a graphviz version 2.44.0 pcakage for it. You might need to compile from source, which isn't great.

**Comment by stdoustderr** [comment]
what version of the container did you use that fixed the graphviz issue? I can live with an older version while we can work on a proper fix..

I will look into what you said also.

@SJrX

**Comment by SJrX** [comment]
This seems to work
```plantuml/plantuml-server:jetty-v1.2019.11```

**Comment by arnaudroques** [comment]
@stdoustderr If you fix the issue, we will of course merge your PR :-)

**Comment by terje2001** [comment]
I believe I have fixed this issue (for Tomcat) in the PR #164 by including 2.44.1 of graphviz

**Comment by MattyRad** [comment]
Thank you @SJrX, using that particular docker tag (`plantuml/plantuml-server:jetty-v1.2019.11`) fixes the issue I was having where state diagrams generated from plantuml.com were nice and well formatted, but state diagrams generated from the docker container where squished and very wide. Much appreciated!

The odd thing is that I did try and build the tomcat docker image locally, but it appeared to have the same issue. That could have been for any number of reasons though, including an error on my end.

**Comment by bharatrajagopalan** [comment]
Hi

this thread is a bit old, but I wanted to use a later version of graphviz so wound up creating my own custom image using jetty 11.0.9 on alpine 3.16 - comes with graphviz 3.0.0 and the edge version has 4.0.0.

I used the existing docker file for jetty and tweaked it a bit to download the war file , this works for me; note that I am using this with the docker-compose.yml for plantuml context root along with nginx. Image is very small ~500 MB or so.


Dockerfile.jetty.alpine
```
FROM jetty:11-jdk17-alpine

USER root

#Setup entrypoint
COPY docker-entrypoint.sh /entrypoint.sh

RUN \
    chmod +x /entrypoint.sh && \
#Install graphviz and font used by official plantuml-server image
#font-noto-cjk removed in favour of noto-ikea
    apk add --no-cache \
        graphviz \
        font-noto-cjk \
        curl  && \
#refresh font cache and cleanup
    fc-cache -f && \
    rm -rf /var/cache/apk/* && \
# Proxy and OldProxy need empty path segments support in URIs
# Hence: allow AMBIGUOUS_EMPTY_SEGMENT
# Changes are only active if `/generate-jetty-start.sh` is called!
    sed -i \
        's/# jetty\.httpConfig\.uriCompliance=DEFAULT/jetty.httpConfig.uriCompliance=DEFAULT,AMBIGUOUS_EMPTY_SEGMENT/g' \ 
        /var/lib/jetty/start.d/server.ini && \
    /generate-jetty-start.sh

#setup plantuml war file in jetty
USER jetty
ENV BASE_URL=ROOT \
    WEBAPP_PATH=$JETTY_BASE/webapps
RUN rm -rf $WEBAPP_PATH && \
    mkdir -p $WEBAPP_PATH && \
    curl -#fL -o $WEBAPP_PATH/plantuml.war -C - https://sourceforge.net/projects/plantuml/files/plantuml.war/download 
ENTRYPOINT ["/entrypoint.sh"]
```

docker-compose.yml
```
version: '3.3'

services:
  plantuml-server:
    build:
      context: .
      dockerfile: Dockerfile.jetty.alpine
    container_name: plantuml-server
    ports:
      - 8080:8080
    environment:
      - BASE_URL=${BASE_URL}
      - TZ=${TZ}
      - JAVA_OPTIONS=${JAVA_OPTIONS}

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    environment:
      - TZ=${TZ}
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

```


.env 
```
#Plantuml context root
BASE_URL=plantuml

#Java options for Jetty/plantuml
JAVA_OPTIONS=-DPLANTUML_LIMIT_SIZE=24576 -Xms1g -Xmx1g -XX:+UseShenandoahGC -verbose:gc

#Timezone
TZ=Europe/Berlin
```

**Comment by fgreinacher** [comment]
The PlantUML Server Docker image is now 5 Graphviz versions behind 😢 

Neither Debian nor Ubuntu seem to have up-to-date versions. Would you consider switching to another base image as suggested above @arnaudroques?

**Comment by arnaudroques** [comment]
> The PlantUML Server Docker image is now 5 Graphviz versions behind cry
> 
> Neither Debian nor Ubuntu seem to have up-to-date versions. Would you consider switching to another base image as suggested above @arnaudroques?

Yes, people can submit some PR with updated version.
The only concern is that we did not test all those versions. But it should work. We'll see :-)
