### ISSUE TITLE
Support HTTP/2 for GitLab

### ISSUE THREAD

**Issue by agramian** [plantuml/plantuml-server#154]
### Issue description

Currently all the docker images in the project are targeting Java 8 which only supports HTTP/1.1 with `HttpURLConnection`.

GitLab serves its raw files using HTTP/2 and as a result the proxy server is not able to render any diagram hosted there.
For my use case I am running a server behind traefik to fetch raw files from private repos I have hosted on GitLab by calling their Repository files API. 

### Steps to reproduce

Below is an example for reproducing the issue using a publicly hosted diagram file from GitLab:

http://www.plantuml.com/plantuml/proxy?src=https://gitlab.com/RockyRoad29/py-puml-tools/-/raw/master/dbpuml2sql/db.puml

### Result
`java.io.IOException: Server returned HTTP response code: 403 for URL:  https://gitlab.com/RockyRoad29/py-puml-tools/-/raw/master/dbpuml2sql/db.puml`

*Note: the behavior on plantuml.com seems to redirect on error but I have reproduced this by running an instance of the project locally and also on a VPS.*

### Proposed solution
Bumping up the docker images to use Java 11 versions resolves the issue since HTTP/2 support was added beginning with Java 9.

**Comment by arnaudroques** [comment]
Thanks for the suggestion !
However, we are not docker expert here.
So please fill free to propose any MR that would upgrade the docker image to java 11.
Thanks!

Arnaud

**Comment by agramian** [comment]
@arnaudroques I've created the PR at #155.  Please take a look.  Thanks.
