### ISSUE TITLE
Website blocked

### ISSUE THREAD

**Issue by waszil** [plantuml/plantuml-server#156]
Hi, I'm not sure if i'm posting it to the reight place, but I cannot access the plantuml.com website behind a corporate proxy, that tells the following:
"
Website blocked
IPS block: cryptomining & blockchain traffic
You tried to visit:https://plantuml.com/
"

**Comment by arnaudroques** [comment]
It sounds like a mistake.
You can tell your proxy admin to contact us (plantuml@gmail.com) if they find any issue on any page.
Thanks!

**Comment by waszil** [comment]
Thanks, indeed, it was an internal problem. Sorry.
