### ISSUE TITLE
Support Tree Diagram 

### ISSUE THREAD

**Issue by achmadns** [plantuml/plantuml-server#159]
Dear PlantUML team. You build such a wonderful piece of software! Many thanks for you attentive work.

I just discovered that you have support for [mind map](https://plantuml.com/mindmap-diagram). It would be great that you can have support for tree diagram e.g. for defining AKKA Actor hierarchy or family tree. Instead of left to right, we only need to draw the illustration from top to down.

Best regards.

**Comment by madoxnet** [comment]
@achmadns  - Does https://plantuml.com/wbs-diagram suit your needs?

**Comment by achmadns** [comment]
Hello @madoxnet, it would be great if we can change the rectangular into rounded rectangular or circle. Thanks.

> @achmadns - Does https://plantuml.com/wbs-diagram suit your needs?

**Comment by HeinrichAD** [comment]
For documentation purpose:

As stated in the documentation and shown in some examples Work Breakdown Structure (WBS) diagrams can be styled.
See: <https://plantuml.com/wbs-diagram>

To change the default rectangular into rounded rectangular you could use the following styling:
```plantuml
<style>
wbsDiagram {
  node {
    RoundCorner 10
  }
}
</style>
```

### Example 1

```plantuml
@startwbs
<style>
wbsDiagram {
  node {
    RoundCorner 10
  }
}
</style>
* <:classical_building:> Business Process Modelling WBS
** Launch the project
*** Complete Stakeholder Research
*** Initial Implementation Plan
** Design phase
*** Model of AsIs Processes Completed
**** Model of AsIs Processes Completed1
**** Model of AsIs Processes Completed2
*** Measure AsIs performance metrics
*** Identify Quick Wins
** Complete innovate phase
@endwbs
```

![image](https://github.com/plantuml/plantuml-server/assets/5962361/6397422c-f6d4-4ae7-b9ee-898c73f100de)


### Example 2
If the corners are still to sharp try some other values for `RoundCorner`. It is also possible to set the `RoundCorner` to $50\\%$. This would result in the following diagram:

![image](https://github.com/plantuml/plantuml-server/assets/5962361/6b0ac1db-69cf-4f68-8ed7-0cddc98cdf53)

### Example 3
If the `RoundCorner` values is really high you would result in something like this:

![image](https://github.com/plantuml/plantuml-server/assets/5962361/a2d8fb35-7f93-4de1-8545-d81248edefce)

**Comment by achmadns** [comment]
@HeinrichAD , many thanks for your guidance! I just got back to github after such a long time.
