### ISSUE TITLE
Support read-only file system

### ISSUE THREAD

**Issue by jemerald** [plantuml/plantuml-server#176]
I tried to get `plantuml/plantuml-server:jetty` running on OpenShift, and go the following error:

```
/docker-entrypoint.sh: 98: /docker-entrypoint.sh: cannot create /var/lib/jetty/jetty.start: Read-only file system
```

The same error can be reproduced by running docker with `--read-only` option:

```
docker run -p 8080:8080 --read-only plantuml/plantuml-server:jetty
```

I've found [this jetty issue](https://github.com/eclipse/jetty.docker/issues/47) which gave me the hint to get things working:

First step was to build a new image:

```dockerfile
FROM plantuml/plantuml-server:jetty
RUN /generate-jetty-start.sh
```

```
docker build -t plantuml/plantuml-server:jetty-readonly .
```

And then run it with 

```
docker run -p 8080:8080 --read-only -v /tmp/jetty plantuml/plantuml-server:jetty-readonly
```

Would you consider include `RUN /generate-jetty-start.sh` in your `Dockerfile.jetty` and some documentation on how to run this in read-only mode?

**Comment by arnaudroques** [comment]
> Would you consider include `RUN /generate-jetty-start.sh` in your `Dockerfile.jetty` and some documentation on how to run this in read-only mode?

Yes, of course.
The easiest way would de that you submit a merge request for that.

Thanks!
