### ISSUE TITLE
Missing GitHub releases and Docker images for v1.2021.8 & v1.2021.9

### ISSUE THREAD

**Issue by stevehipwell** [plantuml/plantuml-server#184]
The GitHub releases haven't been created for the tags `v1.2021.8` & `v1.2021.9` and the Docker images haven't been created, but there are [release notes](https://plantuml.com/changes) for these.

**Comment by stevehipwell** [comment]
@arnaudroques

**Comment by mimam419** [comment]
Hi @arnaudroques,

I guess this issue is due to the changes on Travis CI.

**Comment by phatcher** [comment]
Seems to be there now...

![image](https://user-images.githubusercontent.com/192778/130601265-cd482a3f-7401-4049-94fe-8bc00cb3fed7.png)

**Comment by stevehipwell** [comment]
The images still aren't present on [Docker Hub](https://hub.docker.com/r/plantuml/plantuml-server). The last run job is 3 months old which is the same age as the last tag added to Docker Hub.

**Comment by phatcher** [comment]
But I think that's down to the CI job not being run

**Comment by stevehipwell** [comment]
@phatcher that would be my assumption too. The question is how do we get the CI job run?

**Comment by mimam419** [comment]
@phatcher, as obvious from the Travis CI announcement, the .org domain stopped working in June and the plantuml github organization do not have an account on the .com domain.

Don't the think the organization admin needs to initiate that on Travis CI?

**Comment by arnaudroques** [comment]
> Don't the think the organization admin needs to initiate that on Travis CI?

Well, I need probably help here :-)
I've created a personal account on https://app.travis-ci.com but I don't know how to initiate all this...

On https://app.travis-ci.com/account/migrate I see that I can migrate **plantuml** and **plantuml-server** repository on travis-ci.com, but that "Your account needs to be part of the beta to start migrating public repositories here".

I'm not sure if that's what I want to do, nor if I should sign up for the beta.
Any help is welcome :-)

**Comment by mimam419** [comment]
Hi @arnaudroques, 

Do you mind you send me an email, and maybe we connect over a zoom call to resolve this?

**Comment by stevehipwell** [comment]
Any news on this? I see that v1.2021.10 has been released and is also missing a Docker image.

**Comment by mimam419** [comment]
@stevehipwell, I am making some effort some migrate the CI to Github Actions, and it should be completed over the weekend.

**Comment by stevehipwell** [comment]
Thanks @mimam419!

**Comment by dakky** [comment]
why is this issue closed, althoug the latest versions stoll are not available as dockeriamges?

**Comment by arnaudroques** [comment]
@dakky Thanks to @mimam419 there is just now latest version available on [docker hub](https://hub.docker.com/repository/docker/plantuml/plantuml-server). Could you test and tell us if it's working for you ?

**Comment by stevehipwell** [comment]
@arnaudroques I can confirm that it works correctly as I've run the CI to update my Helm chart.

**Comment by dakky** [comment]
@arnaudroques I can confirm this too. thanks
