### ISSUE TITLE
Add specification of image format on Proxy service

### ISSUE THREAD

**Issue by fuhrmanator** [plantuml/plantuml-server#19]
I just discovered that the proxy service can be useful inside GitHub markdown to document UML models under source control:

http://www.plantuml.com/plantuml/proxy?src=https://raw.github.com/plantuml/plantuml-server/master/src/main/webapp/resource/test2diagrams.txt

![PlantUML image](http://www.plantuml.com/plantuml/proxy?src=https://raw.github.com/plantuml/plantuml-server/master/src/main/webapp/resource/test2diagrams.txt)

The problem with this is that I can't see how to get the SVG version of the image. Would it be possible to add a **format=svg** option?

**Comment by arnaudroques** [comment]
You can use the fmt=svg option. Example:
http://www.plantuml.com/plantuml/proxy?fmt=svg&src=https://raw.githubusercontent.com/w3c/webpayments/gh-pages/PaymentFlows/Card/MerchantHosted-CardPayment-CGProposal.pml

It's indeed not very documented!

**Comment by fuhrmanator** [comment]
OK, nice:

![PlantUML image](http://www.plantuml.com/plantuml/proxy?fmt=svg&src=https://raw.githubusercontent.com/w3c/webpayments/gh-pages/PaymentFlows/Card/MerchantHosted-CardPayment-CGProposal.pml)

**Comment by maxandersen** [comment]
> It's indeed not very documented!

updated the wiki at http://wiki.plantuml.net/site/server to document `fmt` as I keep forgetting the possible values.

**Comment by arnaudroques** [comment]
Thanks for your contribution on documentation!
We know that documentation is very often out of date. That's why we set up this wiki feature : people can now contribute!
The page http://plantuml.com/server has just been updated. Thanks again!
