### ISSUE TITLE
Hostpath includes protocol and is confuses http/https when behind a proxy

### ISSUE THREAD

**Issue by ctn** [plantuml/plantuml-server#207]
https://github.com/plantuml/plantuml-server/blob/da290a15fe8d8b8b156dcaf1516b28134e24afe8/src/main/webapp/index.jsp#L10

I have nginx handle SSL and by the time it gets to this service, the request protocol is HTTP. When this `hostpath` is used to construct URLs, they come back to the client browser as HTTP instead of HTTPS.

A solution is simply to drop `hostpath` and use relative URIs. 

Is there any other reason to use `hostpath` here?

If not, I have a simple PR that will fix this. Thanks.

**Comment by arnaudroques** [comment]
> If not, I have a simple PR that will fix this. Thanks.

You can go ahead, we will be glad to merge it.
Thanks!

**Comment by HeinrichAD** [comment]
> Is there any other reason to use hostpath here?

`hostpath` does also include the context path of the URL.

https://github.com/plantuml/plantuml-server/blob/3763ee737e19b627c484ac44a098ca7fe209ee62/src/main/java/net/sourceforge/plantuml/servlet/PlantUmlServlet.java#L266-L267

So, the problem with your changes in PR #208 is, that it breaks the PlantUML Base URL path feature.

I think your problem should be solved if you add `proxy_set_header  X-Forwarded-Proto  $scheme;` inside your nginx configuration.

Maybe you will find one of the two examples helpful:
- https://github.com/plantuml/plantuml-server/tree/master/examples/nginx-simple
- https://github.com/plantuml/plantuml-server/tree/master/examples/nginx-contextpath

**Comment by ctn** [comment]
`proxy_set_header X-Forwarded-Proto $scheme` does indeed fix the scheme issue, and is a better solution. Thanks.
