### ISSUE TITLE
Retrieve source from image via server?

### ISSUE THREAD

**Issue by fuhrmanator** [plantuml/plantuml-server#21]
I frequently post PlantUML diagrams on StackExchange that are direct URLs to the PlantUML.com server. Because of past problems with services that go off line and negatively affect StackExchange experience, they want the images to be hosted on stack.imgur.com.

I know that there's a PlantUML jar command, but I'm wondering how to get it through the server.

```
    -metadata       To retrieve PlantUML sources from PNG images
```

If so, we could do stuff like draw.io does: [example](https://www.draw.io/?url=http%3A%2F%2Fi.stack.imgur.com%2FwNAIk.png)

I tested (locally) with http://i.stack.imgur.com/HJvKF.png and `-metadata` recovers the source. It's just a question of providing a server hook.

**Comment by arnaudroques** [comment]
We've got the point.
This is a good idea.
We will provide something like:

http://plantuml.com/plantuml/?metadata=http://i.stack.imgur.com/HJvKF.png

(The syntax may change)
That would retrieve source from metadata of http://i.stack.imgur.com/HJvKF.png and display the initial source diagram.

We'll post a message here when ready to be tested

**Comment by arnaudroques** [comment]
This is online. Link http://plantuml.com/plantuml/?metadata=http://i.stack.imgur.com/HJvKF.png is working.
Few tests done, so feedback welcome!

**Comment by fuhrmanator** [comment]
Seems to work well so far. Another example http://plantuml.com/plantuml/?metadata=http://i.stack.imgur.com/495on.png

**Comment by fuhrmanator** [comment]
The samples above don't seem to work anymore. The code comes back with the default `Bob -> Alice : hello` diagram.

**Comment by arnaudroques** [comment]
Hi,
We've slightly changed the way we treats URL.
So you should change http://plantuml.com to http://www.plantuml.com 

For example http://www.plantuml.com/plantuml/?metadata=http://i.stack.imgur.com/HJvKF.png is working for us. (you may have to empty your cache).

**Comment by fuhrmanator** [comment]
Works for me now! Thanks!
