### ISSUE TITLE
New PlantUML Server Editor and default theme change not shown in docker version

### ISSUE THREAD

**Issue by dannief** [plantuml/plantuml-server#215]
I've deployed PlantUML server locally using docker. I noticed that editor is not the same as the one below. But is still the old version (pictured in the 2nd image). Is there a way to enable the new editor page?

In addition, new default theme isn't reflected.

![image](https://user-images.githubusercontent.com/6110488/154521433-bc21ef23-a884-46fe-a290-50ada0f0ec80.png)

![image](https://user-images.githubusercontent.com/6110488/154521627-ce0f08ee-489f-4f28-802f-ff5967ff6626.png)

**Comment by JulienSambre** [comment]
Hi!

Same here. Has anyone found a workaround?

**Comment by arnaudroques** [comment]
That's weird. Docker seems to have been updated https://hub.docker.com/r/plantuml/plantuml-server/tags
Could you try:
```
@startuml
version
@enduml
```
And tell us the result?

**Comment by JulienSambre** [comment]
It gives me that : 

![image](https://user-images.githubusercontent.com/14327288/160116987-bc451ecc-2aac-4932-a82c-debf571d6313.png)

**Comment by bharatrajagopalan** [comment]
@arnaudroques  for me as well -the editor doesn't look the same. How can one access the new editor?

<img width="1309" alt="image" src="https://user-images.githubusercontent.com/15735432/176463517-866059c3-27d5-4a8d-8ecb-216cde9f9adc.png">

<img width="1308" alt="image" src="https://user-images.githubusercontent.com/15735432/176463751-a0416e9c-76c5-4ae1-b289-649ba996ec86.png">

**Comment by niceborn** [comment]
+1
new server editor would solve also some of the accessibility issues (e.g. TAB control to exit the textarea).
