### ISSUE TITLE
My plantuml plug-in cannot preview

### ISSUE THREAD

**Issue by czm578041539** [plantuml/plantuml-server#217]
* I installed the plantuml plug-in in vscode and configured the internal server address of the company. In the evening, I suddenly found that the picture of plantuml could not be displayed when the preview was executed. The error prompt was "fetcherror: cannot follow redirect with body being a readable stream". I couldn't find the relevant error information on Google (A few days ago, it was still working normally. At night, it was suddenly found that there was something wrong with it)

* The same server address can normally display UML images on other colleagues' computers

* And how can I upload screenshots to the description? If I paste the screenshot directly and submit it, will report "Something went really wrong, and we can't process that file."

**Comment by swordjjjkkk** [comment]
i have same problem

**Comment by HeinrichAD** [comment]
I can not reproduce the error. Maybe it is fixed.

My setup was/is:
- VSCode Extension _PlantUML_ in Version v2.17.5
  <details><summary>I am using this one</summary>

  Name: PlantUML
  Id: jebbs.plantuml
  Description: Rich PlantUML support for Visual Studio Code.
  Version: 2.17.5
  Publisher: jebbs
  VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=jebbs.plantuml

  </details>
- VSCode extension settings
  - `Plantuml: Render` to `PlantUMLServer` to force the usage of the server
  - `Plantuml: Server` to `http://localhost:8080/plantuml`

The diagram I tested was the class diagram of [this example](https://github.com/plantuml/plantuml-server/blob/f03bb6840775ee704be23eb4d1404fa594d03c9d/src/main/java/net/sourceforge/plantuml/servlet/diagrams.txt).

----

> The error prompt was "fetcherror: cannot follow redirect with body being a readable stream".
> [...]
> The same server address can normally display UML images on other colleagues' computers

This part does not really sound like an PlantUML Server issue. You could check if you and your other colleagues are using the same version of the VSCode extension. But also network and firewall configurations could create such an issue. (Even some system updates can create such problems, whereby I assume that this was rather not the case.)
