### ISSUE TITLE
My plantuml plug-in cannot preview

### ISSUE THREAD

**Issue by czm578041539** [plantuml/plantuml-server#218]
I installed the plantuml plug-in in vscode and configured the internal server address of the company. In the evening, I suddenly found that the picture of plantuml could not be displayed when the preview was executed. The error prompt was "fetcherror: cannot follow redirect with body being a readable stream". I couldn't find the relevant error information on Google (A few days ago, it was still working normally. At night, it was suddenly found that there was something wrong with it)

The same server address can normally display UML images on other colleagues' computers

And how can I upload screenshots to the description? If I paste the screenshot directly and submit it, will report "Something went really wrong, and we can't process that file."

**Comment by HeinrichAD** [comment]
Duplication of #217
