### ISSUE TITLE
Sometimes Missing Response-Headers for broken PNG images

### ISSUE THREAD

**Issue by volchub** [plantuml/plantuml-server#22]
Hi,
I extended the ``sendDiagram()``method in ``DiagramResponse.java`` with 3 new headers:
```Java
void sendDiagram(String uml) throws IOException {
      if (StringUtils.isDiagramCacheable(uml)) {
         response.addHeader(HttpHeaders.CACHE_CONTROL, "public");
         response.addHeader(HttpHeaders.CACHE_CONTROL, "max-age=" + CACHE_CONTROL_MAX_AGE_IN_SECONDS);
      }
      response.addHeader("Access-Control-Allow-Origin", "*");

      response.setContentType(getContentType());

      final SourceStringReader reader = new SourceStringReader(uml);
      reader.generateImage(response.getOutputStream(), new FileFormatOption(format, false));
   }
```

I want this diagram to be rendered (which will fail because of the wrong syntax):
```
Bob -|-> Alice : hello
```

**My expectation**:

The response headers are always set and not missing.

**My results**:

Used: PlantUML Server / version 8037

With JMeter:
``GET /plantuml/png/SyfFKj3LhT6rKt3CoKnELR1Io4ZDoSdN1G00`` (broken image)
``GET /plantuml/svg/SyfFKj3LhT6rKt3CoKnELR1Io4ZDoSdN1G00`` (broken image)
\# 2000 samples each

**Jetty** localhost:8080

Format | Keep Alive | NO Keep Alive
---------  | -------------- | --------------------
png       | X               | OK                  
svg       | OK             | OK

---

**Tomcat7** localhost:8080

Format | Keep Alive | NO Keep Alive
---------  | -------------- | --------------------
png       | X               | X                  
svg       | OK             | OK

---

X := ``Access-Control-Allow-Origin`` (and often all other response Headers) missing

**Comment by volchub** [comment]
We found a fix for this issue and we are going to provide a patch to plantuml soon.

The problem is within the plantuml library in Class ``PngIOMetadata``.
The outputstream was not closed properly, which leads to the observed behaviour in JMeter..

**Comment by maximesinclair** [comment]
Hi @volchub, did you provide the patch to plantuml ? 
Could I close this issue ?
Thanks for your answer.

**Comment by volchub** [comment]
@maximesinclair, yes the patch is provided to the plantuml library. the issue can be closed :)
