### ISSUE TITLE
PlantUML (1.2022.4)  An error has occured : java.lang.UnsupportedOperationException: NOTE_HEXAGONAL

### ISSUE THREAD

**Issue by wdl83** [plantuml/plantuml-server#221]
Following diagram is correctly rendered online:
https://github.com/wdl83/mdp/blob/master/diagrams/diagrams.plantuml
https://www.plantuml.com/plantuml/uml/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000

Docker version crashes however:
docker run -d -p 8888:8080 plantuml/plantuml-server:jetty

plantuml/plantuml-server   jetty       sha256:cb3f979f7e1a3b827f7bc52be72b1b6ea0b3feaf31b526ce3862e5b8ef839a6c   3f6e8880b1f8   13 hours ago   388MB
[log.txt](https://github.com/plantuml/plantuml-server/files/8463267/log.txt)

**Comment by HeinrichAD** [comment]
This could be an issue with the PlantUML version or with GraphViz. Maybe GraphViz was not correctly installed.

Luckily, it is working with the current PlantUML Server version `v1.2023.8`.

----

### First diagram of the example file

<details><summary>Code</summary>

```plantuml
@startuml simple_request
participant Client
participant Broker
participant Worker

Client -> Broker: request
activate Client

Broker -> Worker: forward request

activate Worker

hnote over Worker
request processing
end note

Worker -> Broker: response

deactivate Worker

Broker -> Client: response

deactivate Client
@enduml
```

</details>

![image](https://github.com/plantuml/plantuml-server/assets/5962361/1a083c13-bf24-4b29-bd79-ee908394b72c)



### Second diagram of the example file

<details><summary>Code</summary>

```plantuml
@startuml worker_lifetime

Worker -> Broker : ready

activate Worker

hnote over Broker
add to
WorkerPool
end note

loop
Broker -> Worker: heartbeat
Worker -> Broker: heartbeat
end

Worker -> Broker: disconnect

hnote over Broker
remove from
WorkerPool
end note

deactivate Worker
destroy Worker

@enduml
```

</details>

![image](https://github.com/plantuml/plantuml-server/assets/5962361/828f9bab-bf8a-4a4c-9a5b-3a0d0b750e4a)
