### ISSUE TITLE
Any way to make the PlantUML server accept raw or URLEncoded text?

### ISSUE THREAD

**Issue by ananthonline** [plantuml/plantuml-server#23]
Having to use Base64 limits usage of a PlantUML server and doesn't allow things like wiki templates to embed PlantUML source that's directly editable. For example,

    http://www.plantuml.com/plantuml/proxy?uml=%40startuml%0ABob%20-%3E%20Alice%20%3A%20hello%0A%40enduml

would generate the standard Bob & Alice sequence diagram.

**Comment by maximesinclair** [comment]
I'm not very favorable to this.
First, if you can URL encode the source of the diagram, you can encode it in [PTE](http://plantuml.com/pte.html).
Second, complex diagrams will generate very very long URLs and other problem could arise.
Note that plantuml is already integrated in a lot of popular wikis and some of these use PlantUML Server.

**Comment by ananthonline** [comment]
While I largely agree with your second point, I must disagree your first. I wanted to embed plantUML diagrams directly into wiki (no scripting support) and this was impossible given the current encoding.

Also, there is no need to break compatibility with the old way of doing things. Adding another endpoint that decodes the UML in a different way and invokes the common function to get a preview gives people more options. Sometimes it isn't easy to get custom plugins to be installed in large organizations.

Depending on the diagram and their usage, people could then use any method that is easiest for them.

**Comment by arnaudroques** [comment]
Could you give us some more details about the wiki you want to integrate PlantUML with ?
No scripting (not even javascript on the client side?) is possible is this wiki ?

**Comment by maximesinclair** [comment]
I understand your point of view but my first idea is influenced by the English proverb "Less is more".

**Comment by ananthonline** [comment]
@arnaudroques This is my corporate wiki (MediaWiki older version) and scripting is not available, alas.
@maximesinclair I understand - I have worked around this problem by standing up my own server that accepts urlencoded strings and renders them to PlantUML images.

PS: I'll try and submit a PR sometime - I hope it becomes part of PlantUML server.
