### ISSUE TITLE
HTTPS redirects back to HTTP

### ISSUE THREAD

**Issue by tacerus** [plantuml/plantuml-server#238]
Hello,

Thanks for the nice software!

I deployed the server using Tomcat 10 and Java 11 behind an Nginx reverse proxy. I used the sample Nginx configuration file, but instead of plain HTTP I use HTTPS.

Nginx:

```
server {
        listen                 <public ip>:443 ssl http2;
        server_name            plantuml.lysergic.dev;

        location                / {
                                proxy_pass              http://appserver:8086;
                                proxy_set_header        HOST                           $host;
                                proxy_set_header        X-Forwarded-Host        $host;
                                proxy_set_header        X-Forwarded-Proto       $scheme;
        }
}
```

Tomcat (server.xml):

```
....
<Connector port="8086" protocol="HTTP/1.1" connectionTimeout="20000"/>
....
```

It seems that whilst PlantUML loads fine, and sets the `hostpath` variable correctly to my full domain including the `https://` schema (as confirmed in the rendered source of the site), the form submissions make my browser want to redirect _back_ to http.

This is the browser activity from the point of opening the page to clicking "Submit Query":

![image](https://user-images.githubusercontent.com/5121046/183267591-08d33910-d36e-4088-b709-1d74c3ee2a83.png)

As one can tell, the initial POST submission is sent to `https://`, but the `location` field contains the `http://` schema:

![image](https://user-images.githubusercontent.com/5121046/183267607-24ca8f6f-4306-4795-a3a8-55836e4d3dff.png)

The resulting GET request then gets stuck with HTTP:

![image](https://user-images.githubusercontent.com/5121046/183267633-ec2bcead-2787-427a-834f-272ffdcea036.png)

Which, given my reverse proxy employs HTTP->HTTPS redirection, ends in an endless redirect loop which my browser aborts.

Did I possibly forget to configure something? Would appreciate any ideas!

Best,
Georg

**Comment by dmitryos** [comment]
Quick workaround meanwhile worked for me:


server
{
  listen xxx ssl;
  server_name yyy;

  **error_page 497 301 =307 https://yyy:xxx$request_uri;**

  location / {
    proxy_set_header  HOST               $host:xxx;
    proxy_set_header  X-Forwarded-Host   $host;
    proxy_set_header  X-Forwarded-Proto  $scheme;

    proxy_pass http://zzz.zzz.zzz.zzz:xxx/;
  }
}

**Comment by tacerus** [comment]
Thanks for your snippet - unfortunately it doesn't do the trick for me - and I do not see any 497 or 301 responses which it could be catching either.

**Comment by tacerus** [comment]
However, I found this workaround:

```
        location                / {
                                proxy_pass              http://appserver:8086;
                                proxy_set_header        HOST                    $host;
                                proxy_set_header        X-Forwarded-Host        $host;
                                proxy_set_header        X-Forwarded-Proto       $scheme;
                                proxy_redirect          http://plantuml.lysergic.dev/ https://plantuml.lysergic.dev/;
        }
```

The `proxy_redirect` "rewrites" the `location` header. This works fine for me - but of course it's technically still a hack.

**Comment by dmitryos** [comment]
That could be some changes in our nginx settings prior to this section? Just for a reference I used this link to solve my redirection: https://stackoverflow.com/questions/15429043/how-to-redirect-on-the-same-port-from-http-to-https-with-nginx-reverse-proxy

**Comment by tacerus** [comment]
I use a generic HTTP to HTTPS redirect which applies to all of my web applications:

**Comment by HeinrichAD** [comment]
For documentation purpose:

There exists multiple [examples](https://github.com/plantuml/plantuml-server/tree/master/examples) now:
- [Nginx simple reverse proxy example](https://github.com/plantuml/plantuml-server/blob/master/examples/nginx-simple)
- [Nginx reverse proxy example with defined location directive (different context path)](https://github.com/plantuml/plantuml-server/blob/master/examples/nginx-contextpath)
- [Kubernetes simple deployment](https://github.com/plantuml/plantuml-server/blob/master/examples/kubernetes-simple)
