### ISSUE TITLE
ProxyServlet Timeout is hardcoded to 10s.

### ISSUE THREAD

**Issue by aadrian** [plantuml/plantuml-server#240]
Hi,

The ProxyServlet connection timeout seems to be hardoded to "10 seconds":

https://github.com/plantuml/plantuml-server/blob/master/src/main/java/net/sourceforge/plantuml/servlet/ProxyServlet.java#L190

Is there any way to override this value or make it configurable ?

of if there's no way to override it, would it be acceptable a PR that would accept this timout limit as a request parameter?

Thank you.

**Comment by arnaudroques** [comment]
> of if there's no way to override it, would it be acceptable a PR that would accept this timout limit as a request parameter?

Yes, you can propose a PR to improve this.
Thanks!
