### ISSUE TITLE
本地部署plantuml server  一直失败

### ISSUE THREAD

**Issue by linbaobei** [plantuml/plantuml-server#242]
环境：
VMware下的centos7
Tomcat 8/9/10 都试过还是失败。
jdk11 jdk8 jdk19 jdk12
要么就是503报错，要么就是500

我很绝望，来个大佬救命。。。。

下面是 tomcat10+jdk11部署时访问的错误提示
Sorry, but things didn't work out as planned.

Wed Oct 05 12:34:24 CST 2022
Request that failed: /plantuml-jsp-v1.2022.7/uml/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000
Status code: 500
Exception: org.apache.jasper.JasperException: /index.jsp (行.: [52], 列: [13]) 文.件[resource/githubribbon.html] 未找到

**Comment by HeinrichAD** [comment]
Duplication of #241.
