### ISSUE TITLE
Docker image not working - Dot Executable not exist

### ISSUE THREAD

**Issue by GNHua** [plantuml/plantuml-server#244]
Tried both commands to set up a docker container for local:
```
docker run -d -p 8080:8080 plantuml/plantuml-server:jetty
docker run -d -p 8080:8080 plantuml/plantuml-server:tomcat
```

With only one class, it works.
```
@startuml
class Dummy {
  String data
  void methods()
}
@enduml
```
Results:
<img width="127" alt="Screen Shot 2022-10-13 at 3 10 45 PM" src="https://user-images.githubusercontent.com/9483735/195711382-02b425df-2364-43bb-a212-4b3b9786f831.png">

But if adding another class, it stops working
```
@startuml
class Dummy {
  String data
  void methods()
}

class Flight {
   flightNumber : Integer
   departureTime : Date
}
@enduml
```

Result:
<img width="279" alt="Screen Shot 2022-10-13 at 3 06 45 PM" src="https://user-images.githubusercontent.com/9483735/195711129-96f2b613-6c2c-48a0-9db3-c592587dbd55.png">

Most examples on https://plantuml.com/ does not work.

Computer: MacBook Pro 16in M1 Max, macOS 12.6 Monterey
Docker: M1 version 4.12.0 (85629)

**Comment by mingmxu** [comment]
`graphviz` is not installed properly in the image. Try to pull the latest image and run it again
```
docker run --pull=always  -d -p 8080:8080 plantuml/plantuml-server:jetty
```
