### ISSUE TITLE
Soap server for large diagram

### ISSUE THREAD

**Issue by cgoguyer** [plantuml/plantuml-server#25]
Large UML diagram could not be rendered on the online server as the encoded syntax for describing diagram is too big to be send within the url.
issue: http://plantuml.sourceforge.net/qa/?qa=4839/very-large-diagram

I will be great to use a SOAP request to send the encoded diagram description and then bypass this url size limit.

**Comment by maximesinclair** [comment]
SOAP is not necessary, the idea is to have a POST interface so the server can accept the description of a very big diagram (more than 100Kbytes of data).

**Comment by cgoguyer** [comment]
Great news (just what I need), is there already a planned date for this feature ?

**Comment by brunobertechini** [comment]
+1
