### ISSUE TITLE
Create uml from git link

### ISSUE THREAD

**Issue by asd-and-Rizzo** [plantuml/plantuml-server#27]
Given I have public link to text file with uml on gitlab or github, I may paste link into plantuml server and get image. 

It would be either reasonable to create issue on github and gitlab to render plantuml inside their web interfaces, like these where done for some other kinds of text -  e.g. 2d/3d models.

**Comment by baguio** [comment]
Are you refering to this?
https://github.com/plantuml/plantuml-server/issues/4#issuecomment-165893842

**Comment by asd-and-Rizzo** [comment]
Please close as duplicate
