### ISSUE TITLE
Graphviz is missing in Docker image

### ISSUE THREAD

**Issue by Frank-Mayer** [plantuml/plantuml-server#293]
A tried writing a class diagram:
```puml
@startuml
class A {}

class B {}
@enduml
```

And got this message in the output:
```
Dot Executable: /opt/local/bin/dot
Dot executable does not exist
Cannot find Graphviz. You should try
 
@startuml
testdot
@enduml
 
or
 
java -jar plantuml.jar -testdot
```

<br>

This input:
```puml
@startuml
testdot
@enduml
```

results in this output:

```
PlantUML version 1.2023.7 (Fri May 12 17:23:42 UTC 2023)
Error: Dot executable does not exist
Error: only sequence diagrams will be generated
```

<br>

With a previous version, there was no need to install Graphviz.

I am running Docker 23.0.4 on Arch Linux (Kernel 6.2.10-arch1-1).
PlantUML version 1.2023.7

Is there something wrong on my side, or should Graphviz be included in the image?

**Comment by HeinrichAD** [comment]
Graphviz should be included in the image.
See #290
It seems to be already fixed but not published yet.
As a work around you could use the last version instead of the latest:
`plantuml/plantuml-server:v1.2023.6`

**Comment by Frank-Mayer** [comment]
I have installed Graphviz into the container manually. It works.
But I hope that a correction will be published soon.
