### ISSUE TITLE
Issue re-evaluation

### ISSUE THREAD

**Issue by HeinrichAD** [plantuml/plantuml-server#303]
As stated in PR #294 there are a lot of open issues which are already solved. I started to re-evaluate some of them and will use this issue for documentation.
CC: @The-Lum 

### Issue Types

| No. | Meaning                                   |
| --- | ----------------------------------------- |
| 1.  | Already solved, answered or implemented |
| 2.  | No longer relevant                        |
| 3.  | No response                               |
| 4.  | Can not reproduce                         |
| 5.  | Open Issue                                |

## Issue Table

| Issue | 1   | 2   | 3   | 4   | 5   | Notes                                                                                            |
| ----- | --- | --- | --- | --- | --- | ------------------------------------------------------------------------------------------------ |
| #303  | ✗   |     |     |     |     | This issue :D                                                                                    |
| #283  |     |     |     |     | ✗   | PlantUML Core issue                                                                              |
| #277  | ✗   |     |     |     | ✗   | Issue is solved. Need documentation on DockerHub which can only be provided by the maintainer (no PR possible)|
| #265  |     |     |     |     | ✗   | Need more documentation                                                                          |
| #261  |     |     |     |     | ✗   | Feature request to be able to disable caching for http response header.                          |
| #258  |     |     |     |     | ✗   | Waiting for feedback/more information                                                            |
| #249  | ✗   |     |     |     |     | New front-end; Note: the editor config `"tabFocusMode": true` enables the the default tabbing behaviour (Tab to next element) |
| #244  | ✗   |     | ✗   |     |     |                                                                                                  |
| #243  |     |     |     |     | ✗   | Tomcat and overwriting `Access-Control-Allow-Origin`                                             |
| #242  |     | ✗   |     |     |     | Duplication of #241                                                                              |
| #241  |     |     |     |     | ✗   | Maybe solve, but waiting for response                                                            |
| #238  | ✗   |     |     |     |     |                                                                                                  |
| #232  | ✗   |     |     |     |     |                                                                                                  |
| #227  |     |     |     |     | ✗   | Feature request w.r.t. security improvement                                                      |
| #225  |     |     |     |     | ✗   | PlantUML Core issue                                                                              |
| #222  | ✗   |     |     |     |     |                                                                                                  |
| #221  | ✗   |     |     |     |     |                                                                                                  |
| #219  | ✗   |     |     |     |     |                                                                                                  |
| #218  |     | ✗   |     |     |     | Duplication of #217.                                                                            |
| #217  |     |     |     | ✗   |     | Issue description does not sound like a PlantUML Server issue                                    |
| #215  | ✗   |     |     |     |     |                                                                                                  |
| #211  | ✗   |     |     |     |     | Original issue seems to be solved.                                                               |
| #210  | ✗   |     |     |     |     |                                                                                                  |
| #205  | ✗   |     |     |     |     |                                                                                                  |
| #202  | ✗   |     |     | ✗   |     | But I am pretty sure the last answer solved it. At least there is a working example              |
| #200  |     |     |     |     | ✗   | PlantUML Core issue                                                                              |
| #190  | ✗   |     |     |     |     |                                                                                                  |
| #179  | ✗   |     |     |     |     |                                                                                                  |
| #173  |     |     |     | ✗   |     | But to be honest, there were multiple major "front-end" changes. So, it could also be simply fixed. |
| #172  | ✗   |     |     |     |     |                                                                                                  |
| #171  | ✗   | ✗   |     |     |     | `BASE_URL` is now an environment variable                                                        |
| #170  | ✗   |     |     |     |     | The [PlantUML Core Repository](https://github.com/plantuml/plantuml) offerers now its own docker image. See https://github.com/plantuml/plantuml/pull/488#issuecomment-1337913405. |
| #169  | ✗   |     |     |     |     |                                                                                                  |
| #168  |     |     |     |     | ✗   | Security Issue! But in my opionion the behaviour is correct.                                     |
| #167  | ✗   |     |     |     |     |                                                                                                  |
| #161  | ✗   |     |     |     |     |                                                                                                  |
| #159  | ✗   |     |     |     |     |                                                                                                  |
| #157  | ✗   |     |     |     |     |                                                                                                  |
| #154  | ✗   |     |     |     |     |                                                                                                  |
| #152  | ✗   |     |     |     |     |                                                                                                  |
| #149  | ✗   |     |     |     |     |                                                                                                  |
| #147  |     |     | ✗   |     | ✗   | Feature request. Author wanted to create a PR but ...                                            |
| #146  | ✗   |     |     |     |     |                                                                                                  |
| #143  | ✗   |     |     |     |     |                                                                                                  |
| #142  | ✗   |     |     |     |     |                                                                                                  |
| #136  |     |     |     | ✗   |     | Also, not much information offered.                                                              |
| #132  | ✗   |     |     |     |     |                                                                                                  |
| #131  |     | ✗   |     |     |     | Author asked for closing.                                                                        |
| #129  | ✗   |     |     |     |     |                                                                                                  |
| #127  |     |     |     |     | ✗   | API documentation request                                                                        |
| #125  | ✗   |     |     |     |     |                                                                                                  |
| #122  | ✗   |     |     |     |     |                                                                                                  |
| #121  | ✗   | ✗   |     | ✗   |     | After so much time and changes this issue can not be relevant anymore. And the problem was most likly not a PlantUML issue. |
| #116  | ✗   |     |     |     |     |                                                                                                  |
| #111  | ✗   |     |     | ✗   |     | Solved via workaround. But original issue is also not reproducible e.g. via jetty docker container |
| #109  | ✗   |     |     |     |     |                                                                                                  |
| #102  | ✗   |     |     |     |     |                                                                                                  |
| #96   |     |     |     |     | ✗   | PlantUML Core issue/feature request                                                              |
| #95   |     |     |     |     | ✗   | PlantUML Core issue/feature request                                                              |
| #87   |     |     |     |     | ✗   | PlantUML Server with large diagrams (too large for a get request) $\rightarrow$ possible solution: let the editor always use post requests |
| #86   | ✗   |     |     |     |     |                                                                                                  |
| #85   |     |     |     |     | ✗   | Most likely a "wont fix" issue or possible PlantUML Core feature request                         |
| #82   |     |     |     | ✗   |     |                                                                                                  |
| #80   | ✗   |     |     |     |     |                                                                                                  |
| #78   | ✗   |     |     |     |     | Solved with PR #234                                                                              |
| #77   | ✗   |     |     |     |     | Answered with not possible/not happening since Tomcat stopped offering an official Docker image based on Alpine Linux 4 years ago. |
| #76   | ✗   |     |     |     |     |                                                                                                  |
| #75   |     |     |     |     | ✗   | Feature request:<br><ul><li>`@startuml(id=MY_OWN_ID)` and `!include foo.txt!MY_OWN_ID` [[doc]](https://plantuml.com/preprocessing#393335a6fd28a804)</li><li>`!startsub BASIC` and `!includesub file1.puml!BASIC` [[doc]](https://plantuml.com/preprocessing#98ecfc06b2af9277)</li></ul> |
| #73   | ✗   |     |     |     |     |                                                                                                  |
| #72   |     |     |     |     | ✗   | Feature request (currently not possible, but there is the `CheckSyntaxServlet`)                  |
| #70   | ✗   |     |     |     |     |                                                                                                  |
| #69   | ✗   |     |     |     |     | Main issue solved. Additional issue later in the issue not reproducible. Asked for a new issue including example. |
| #68   |     |     |     |     | ✗   | This can only be done by somebody with direct repository access since a force push is necessary. As a workaround it is possible to clone without the complete history via `git clone --depth X`. |
| #67   | ✗   |     |     |     |     |                                                                                                  |
| #66   | ✗   |     |     |     |     |                                                                                                  |
| #65   | ✗   |     |     | ✗   |     | no plantuml problem, but a issue with docker                                             |
| #59   | ✗   |     |     |     |     | solved via workaround and the original issue is also not reproducible anymore (probably solved)  |
| #57   | ✗   |     |     |     |     | but the topic in general need some more documentation                                         |
| #53   |     |     |     | ✗   |     | could also simply be fixed after 6 years and/or due to the new metadata servlet                  |
| #51   | ✗   |     |     |     |     |                                                                                                  |
| #46   | ✗   |     |     |     |     |                                                                                                  |
| #34   | ✗   |     |     |     |     |                                                                                                  |
| #32   | ✗   |     |     |     |     |                                                                                                  |
| #25   | ✗   |     |     |     |     |                                                                                                  |
| #24   | ✗   | ✗   |     |     |     | old frontend issue                                                                               |
| #20   |     |     |     |     | ✗   | reproducible and still valid                                                                     |
| #9    | ✗   | ✗   |     |     |     | feature request solved, CodeMirror discussion no longer relevant (due to vscode-editor)          |
| #4    | ✗   |     |     |     |     |                                                                                                  |

## Additional Notes
- An API/Servlet Documentation (e.g. OpenAPI Specification) would be great and could answer quite a few issues/questions.
- We may need an example on how to use `PLANTUML_SECURITY_PROFILE`, `plantuml.include.path` and `!include` (and Docker).
- We may need more documentation about what PlantUML Server is releasing and what which release ("war" file) should be used for.

**Comment by HeinrichAD** [comment]
### Re-evaluation result
Of the 88 open issues:
- 21 are still valid
  - 2/21 are only solvable by a maintainer (no PR possible)
  - 5/21 are PlantUML Core issue marked with `PlantUML Core issue` in the table.
    @arnaudroques should these be move the the Core project and closed here?
  - 3/21 waiting for feedback/response
- 67 are already solved

Note: Some are already closed by the authors.


### PR re-evaluation
All three open PRs are also no longer appropriate to the current PlantUML implementation.
- _Automatically update URL when UML content changed_
  This is already implemented (but in an other way)
- _Codemirror support_
  PlantUML Server is no longer using Codemirror but the VSCode web editor (monaco-editor)
- _Support Openshift_
  As far as I understand from the following code lines PlantUML Server also supports Openshift (now)
  https://github.com/plantuml/plantuml-server/blob/f03bb6840775ee704be23eb4d1404fa594d03c9d/Dockerfile.jetty#L72-L76


----

@arnaudroques the following issues can only be solved by a maintainer. Pull requests are not possible here.
Could you please review them and decide if you will change something or not?
- #277
- #68

----

Also, should I try to create a blank PR to close all of these issues at once? Should I leave some of them open?

**Comment by arnaudroques** [comment]
> the following issues can only be solved by a maintainer. Pull requests are not possible here.
> Could you please review them and decide if you will change something or not?

Many thanks Heinrich for your work. I've sent you an invitation to become maintainer.
Right now, I am focusing on the core library itself, and now you have a better knowledge about the server than me :-)

For example, you can close some issues.

Also please take any actions you think useful. If you need some advices, you can also start some new discussion and ping @The-Lum : Theo has also very good ideas! And do not be afraid of any changes: we can always rollback.

Best regards,
Arnaud

**Comment by HeinrichAD** [comment]
Firstly, thank you for your trust.

But issue #277 ask for more documentation or at least a hint to look on the GitHub Repository for more documentation on the [DockerHub page](https://hub.docker.com/r/plantuml/plantuml-server). This is also not possible for me even as a maintainer.

Also, I like the idea of code review and active discussions about changes. So, it could be that I will still only create a PR, unless the changes are unnecessary to review like typos etc. But it is good to know that I can also ask The-Lum to review PRs.
