### ISSUE TITLE
Is there a feature to view the UML generation history?

### ISSUE THREAD

**Issue by usingsystem007** [plantuml/plantuml-server#306]
It would be nice to have the ability to see the UML created so far. I have a mongo db inside, is the work history stored in this db?

**Comment by HeinrichAD** [comment]
The only "history" feature I am aware of is the ability to do <kbd>Ctrl</kbd>+<kbd>z</kbd> and <kbd>Ctrl</kbd>+<kbd>y</kbd> inside the code editor.

In addition, the PlantUML server works stateless and does not store any data. Therefore there is also no database. Maybe your mentioned Mongo DB is used for/by something else?
