### ISSUE TITLE
PNG preview not working

### ISSUE THREAD

**Issue by rednyte** [plantuml/plantuml-server#309]
**Describe the bug**
After installing the plantuml-jsp-server v1.2023.10 war with tomcat, running and loading the default page, the PNG preview does not load. Directly going to the png link does not work either. This also doesn't work for the PDF preview. The ascii art and svg work. This was also the case with v1.2023.8. It is running on AlmaLinux 9.2, with JDK 11.0.20, tomcat 10.1.10, and graphviz 2.44.0-25.

**To Reproduce**
Load the default page.

**Expected behavior**
I expect to see the default Bob and Alice example (Bob -> Alice : hello)

**Desktop (please complete the following information):**

- OS: macOS and Linux
- Browser: Chrome, Safari, Firefox
- Version: latest version

**Comment by HeinrichAD** [comment]
I tried to reproduce your problem but I can get it. It's always working for me :sweat_smile: 

What I did:
1. Download  [plantuml-jsp-v1.2023.10.war](https://github.com/plantuml/plantuml-server/releases/download/v1.2023.10/plantuml-jsp-v1.2023.10.war) from the [release page](https://github.com/plantuml/plantuml-server/releases/tag/v1.2023.10)
2. rename `plantuml-jsp-v1.2023.10.war` to `plantuml.war`
3. copy `plantuml.war` to my local tomcat server (w.r.t. the context path plantuml)
4. open my local tomcat instance with the context path `/plantuml` inside my browser: <http://localhost:8080/plantuml>
5. see PlantUML Server working happily

I also tested the Tomcat Dockerfile image which also uses the `plantuml-jsp-v1.2023.10.war` file. I couldn't find any problems there either.

Could you please check your tomcat setup. If the issue still is the same please provide us with more information. A detailed guide how to reproduce the error would also be great.

**Comment by rednyte** [comment]
This was indeed an issue with tomcat. I guess I had deleted my temp folder where my PID was being stored and it didn't automatically recreate it. Once I created the folder all was well. Thank you!
