### ISSUE TITLE
Emojis in UML Diagrams

### ISSUE THREAD

**Issue by besi** [plantuml/plantuml-server#32]
Emojis, as cute and silly as they seem are to me a very powerful means of providing a quick summary of what I want to display.

Unfortunately it's currently not possible to include emojis in plantuml diagrams:

```plantuml
@startuml
usecase "🛠 Implement the changes" as Implement

:Company: --> Implement
@enduml
```

The above does not generate the desired UML Image.

### Current Result
![sowkiimgastduiejjareb4vlkfemv_o21s_swfpktdiy4emiz5i5v8p4lfjkoym5n6a431unbnd-ra5yngmlwgwk7pa4gsfu2ix8bw00](https://cloud.githubusercontent.com/assets/160412/23751233/a4c90fc4-04d0-11e7-8bc4-1b6bc6ef6bcc.png)

### Desired result

![sowkiimgastduiejjareb4vlkd9j00fft8asrdpkl1a5aenkxuicnbpqr68bxshyx0mnbvlpvcv1obwbboakhxsix4dgnwh8k2u0](https://cloud.githubusercontent.com/assets/160412/23751171/659462f4-04d0-11e7-9e43-f9b9b02469ad.png)

**Comment by arnaudroques** [comment]
I think it's an issue of which fonts are installed on the server.
For example, the following example is working:
http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuIejJarEB4vLKFemVqQpWcTkGKvgRcfUYK99Hgf2SaPYNdfgiP92OZ52XYlQEJ-t836lCbP1LzSEITmXDIy5Q280
Do you know a font that encodes that Emoji ?

**Comment by arnaudroques** [comment]
Starting with V8054, we have improved support for Emoji.
This is not perfect, but the following example are working:
```
@startuml
usecase "<font:Segoe UI Symbol>🛠</font> Implement the changes" as Implement
:Company: --> Implement
@enduml
```
and
```
@startuml
usecase "<U+1F601> <U+1F680> <font:Segoe UI Symbol><U+1F6E0></font> Implement the changes" as Implement
[Company] --> Implement
@enduml
```
http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuIejJarEB4vLKB89rJPqCpCmj5E0i2mCWAoq_BmIg-3KzFnKXL1FXU3AtAJy73k8lAk1dOq-IDvEmJEt82SrDpMlHA4a8rKXEICnBpsrM4aXiHWXmnNjd9zRa9XN6QkWgukaWyiXDIy5w0u0

We are also wondering if we could not support syntax like:
`usecase ":smile: You can use special notation for Emoji :hammer-and-wrench:"
`
or
`usecase "<:smile:> You can use special notation for Emoji <:hammer-and-wrench:>"
`
Any though about this ?

**Comment by VladimirAlexiev** [comment]
@arnaudroques You already got some openicons that are invoked with `<&person>`.

Using Unicode char names is a good idea, but what should be the syntax? The official Unicode name of that symbol is `HAMMER AND WRENCH`. So maybe `<U+HAMMER AND WRENCH>` ?

**Comment by troytop** [comment]
Perhaps this is a separate feature request, but it would be very cool to be able to specify an emoji for a declared participant in sequence diagrams.

**Comment by arnaudroques** [comment]
@troytop Could you post a minimal example of what you are expecting ?
Thanks!

**Comment by troytop** [comment]
@arnaudroques was thinking of something like:

```uml
@startuml
skinparam actorStyle :woman_factory_worker:
skinparam participantStyle :telephone:
skinparam databaseStyle :file_cabinet:
...
```
Or perhaps instead or also using unicode characters:

```uml
skinparam actorStyle <U+1F469>
```

**Comment by troytop** [comment]
I've been thinking about this a bit more, and it would be great if there were a generic way to specify a file or icon in a `skinparam` declaration without having to create one in Java. I think that be a separate feature request / issue though.

**Comment by huyz** [comment]
> `usecase "<:smile:> You can use special notation for Emoji <:hammer-and-wrench:>" `

This seems to be supported already:
```plantuml
usecase "<:smile:> You can use special notation for Emoji <:hammer_and_wrench:>"
```
gives:
![screenshot 2022-06-13T100231Z](https://user-images.githubusercontent.com/128394/173330068-5610a966-373d-45a8-b095-2d047f220f1f.png)
