### ISSUE TITLE
skinparam declaration depends on order 

### ISSUE THREAD

**Issue by kkrafft1999** [plantuml/plantuml-server#323]
**Describe the bug**
_skinparam ActivityBackgroundColor_ overrides _skinparam ActivityDiamondBackgroundColor_ and
_skinparam ActivityBorderThickness_ overrides _skinparam ActivityArrowThickness_

If I change the order of the skinparam definitaion then it works, But it should make no difference how the skinparam definitions are ordered.

**Comment by The-Lum** [comment]
_[Just for the record]_
See also plantuml/plantuml#1084

Perhaps use style instead.

Regards,
Th.

**Comment by The-Lum** [comment]
Hi @kkrafft1999, and all,

Yes you have right. Thank for the report.
But:
- Could you now use the `style` new functionally?

From:
```puml
@startuml
skinparam ActivityDiamondBackgroundColor red
skinparam ActivityBackgroundColor blue

skinparam ActivityArrowThickness 2
skinparam ActivityBorderThickness 1

if (counter?) equals (5) then
:print 5;
else 
:print not 5;
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/RSzD2i9030NW_PmYotQfq8qkRDKZU85n9jhGQT9cCegtzmT4a2xVu-F1QxDvjJ8cbmVYoQiVeGj6DxB7aVme7FS-35ULml4WIHGKumB-L-TKq2suJbNkfvx2m9Wph9UcH2FgpwoSemjKuJLkgBiQS2u-PQYQ6gn7Tfj9YGsQhSEK4RwPvTEroF5zy0a0)](https://www.planttext.com/?text=RSzD2i9030NW_PmYotQfq8qkRDKZU85n9jhGQT9cCegtzmT4a2xVu-F1QxDvjJ8cbmVYoQiVeGj6DxB7aVme7FS-35ULml4WIHGKumB-L-TKq2suJbNkfvx2m9Wph9UcH2FgpwoSemjKuJLkgBiQS2u-PQYQ6gn7Tfj9YGsQhSEK4RwPvTEroF5zy0a0)

To:
```puml
@startuml
<style>
activityDiagram {
  arrow {
    LineThickness 2
  }
  activity {
    BackgroundColor blue
    Thickness 1
  }
  diamond {BackgroundColor red}
}
</style>
if (counter?) equals (5) then
:print 5;
else 
:print not 5;
@enduml

```
>[![](https://www.planttext.com/api/plantuml/svg/NO_13e8m44Jl_OezmibemaM94lNeqH-exGeDPQlRLaC8_owG6XDlipFpajdA1yaXTbQKFlGMzqAgO5ucz6SZQvOT3090ChlteW0kXl3Q6DKIUW-RoHldHg9IwIXLMxEBf4_EEeQRZRW4FtATI6ravqZ3yCymwb6CebobOUOEcPhYW7p80PzHMWzPaKDeaCJsmOO253k1rYDyRtABLo7f-SaF)](https://www.planttext.com/?text=NO_13e8m44Jl_OezmibemaM94lNeqH-exGeDPQlRLaC8_owG6XDlipFpajdA1yaXTbQKFlGMzqAgO5ucz6SZQvOT3090ChlteW0kXl3Q6DKIUW-RoHldHg9IwIXLMxEBf4_EEeQRZRW4FtATI6ravqZ3yCymwb6CebobOUOEcPhYW7p80PzHMWzPaKDeaCJsmOO253k1rYDyRtABLo7f-SaF)

_[The order of `diamond` is always relevant!]_ 🙄 

---
And FYI, see also:

>Unfortunately, we won't fix issues in skinparam. Skinparam are still supported for very simple case (and for ascending compatibility) but we would like people to migrate to style instead. (The main reason is that code for skinparam is too old and not very well written).

On:
- https://github.com/plantuml/plantuml/issues/1464#issuecomment-1601464639

---

_Enjoy,_
Regards,
Th.

**Comment by kkrafft1999** [comment]
Thank you @The-Lum , this works for me. :) Thanks for your help.
Regards, Konrad.
