### ISSUE TITLE
Auto generated docker image in docker hub

### ISSUE THREAD

**Issue by paulobezerr** [plantuml/plantuml-server#33]
Create organization in docker hub: https://hub.docker.com/organizations/add/
And set to build dockerfile in every push.

**Comment by Ducatel** [comment]
Yes, it will be very usefull.
You can do that easily by using travis job

A sample of `.travis.yml` configuration

````
language: java
services:
    - docker

after_success:
  - docker login  -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t plantuml/plantuml-server:latest . ;
    docker push plantuml/plantuml-server:latest;
    fi
````

or better, you can build the war with travis and create docker image with [tomcat official image](https://hub.docker.com/_/tomcat/) which deploy the war.

**Comment by Ducatel** [comment]
So I have deploy a docker repo. 
https://hub.docker.com/r/tracesoftware/plantuml-server/
https://github.com/TraceSoftwareInternational/plantuml-server

**Comment by paulobezerr** [comment]
I have seen your repo in docker hub, great ideia.
But what I mean is to have an oficial docker image, once the images are generated and delivered automatically. 😃

**Comment by Ducatel** [comment]
I'm totally agree with you.
If an official docker image will be available, I will delete my repo and used the official image.
PS: my image is generated and delivered automatically weekly ;)

**Comment by paulobezerr** [comment]
I'm using your image. Thank you!!!

**Comment by Ducatel** [comment]
PR #40 open ;)

**Comment by Ducatel** [comment]
Docker image available https://hub.docker.com/r/plantuml/plantuml-server/

**Comment by thiyagaraj** [comment]
@Ducatel Should we also publish the tomcat8 version seperately for folks who use it, I only renamed the file and I am not the original author, that dockerfile could use some edits to actually do the maven build as part of the docker build, right now, it depends on it being done externally prior to running `docker build`...

**Comment by Ducatel** [comment]
Yes, I will add it ;)

**Comment by Ducatel** [comment]
Added with PR #42
