### ISSUE TITLE
Monospaced font missing in the Docker image?

### ISSUE THREAD

**Issue by arnaudroques** [plantuml/plantuml-server#334]
**Describe the bug**
It looks like monospaced fonts are not working with the Docker image

**To Reproduce**

Simple example:
```
@startuml
Bob -> Alice : hello ""monospaced""
@enduml
```

**Expected behavior**

The text "monospaced" should be printed using a monospaced font.

**Additional context**

What about ading `fonts-dejavu-core` and `fonts-noto-mono` to the Dockerfile?

Any though anyone ?

**Comment by HeinrichAD** [comment]
Does anybody know of this is a new behavior?

Since we already had a few questions about fonts, there exists an example on how to add additional fonts to your docker container. Or to be more precise, on how to map your local installed fonts to the docker container.

https://github.com/plantuml/plantuml-server/blob/master/examples%2Fadditional-fonts%2FREADME.md

**Comment by The-Lum** [comment]
Hi all,

It seems that ever there is one monospaced font (e.g. `Monospaced`) the issue occurs...

See all the minimal tests _(with the current web-server)_:

```puml
@startuml
listfonts
@enduml
```
>[![](https://www.planttext.com/api/plantuml/png/SoWkIImgAStDuSh9B2v9oyyhAUPoICrB0Oe00000)](https://www.planttext.com/?text=SoWkIImgAStDuSh9B2v9oyyhAUPoICrB0Oe00000) 

```puml
@startuml
hide footbox
Bob -> Alice : hello ""monospaced""
footer \n1.202425beta1 / %version()
@enduml
```
:x: KO on PNG
>[![](https://www.planttext.com/api/plantuml/png/5SpB2W8X50RWlK_n8mJJeeioRLg4zHnjl9n1GJsXpZ2FN-q_FjE7RMCjMSGK20lpSBoB5pkS7dZcv0btHCgP8MNXolrZFGKfnTzImxkgixxgMTyS3QjmmM6ZrXFNwIWCrV3Blm00)](https://www.planttext.com/?text=5SpB2W8X50RWlK_n8mJJeeioRLg4zHnjl9n1GJsXpZ2FN-q_FjE7RMCjMSGK20lpSBoB5pkS7dZcv0btHCgP8MNXolrZFGKfnTzImxkgixxgMTyS3QjmmM6ZrXFNwIWCrV3Blm00) 

✔️ OK on SVG
>[![](https://www.planttext.com/api/plantuml/svg/5SpB2W8X50RWlK_n8mJJeeioRLg4zHnjl9n1GJsXpZ2FN-q_FjE7RMCjMSGK20lpSBoB5pkS7dZcv0btHCgP8MNXolrZFGKfnTzImxkgixxgMTyS3QjmmM6ZrXFNwIWCrV3Blm00)](https://www.planttext.com/?text=5SpB2W8X50RWlK_n8mJJeeioRLg4zHnjl9n1GJsXpZ2FN-q_FjE7RMCjMSGK20lpSBoB5pkS7dZcv0btHCgP8MNXolrZFGKfnTzImxkgixxgMTyS3QjmmM6ZrXFNwIWCrV3Blm00) 

If that can help, for test and according to the current plantuml webserver (`plantuml.com`).

Regards,
Th.

**Comment by HeinrichAD** [comment]
I just tested it with some more obvious characters on the lastest docker version. In my opinion monospace is working quite well for png as well as svg.

```plantuml
@startuml
hide footbox
Bob -> Alice : hello mmiimm ""monospaced mmiiimm""
footer \n%version()
@enduml
```

|PNG|SVG|
|-|-|
|![png](https://github.com/plantuml/plantuml-server/assets/5962361/b202eaa8-dda4-447d-b1ea-00c221e44c31)|![svg](https://github.com/plantuml/plantuml-server/assets/5962361/30d38873-7975-4151-a3cd-facb91a8cd40)|

Or do I miss something?

**Comment by The-Lum** [comment]
Hi @HeinrichAD 

It seems that you are right.

We are so used to seeing the `courier` serif font _(on the old plantuml webserver)_ that the change with a sans-serif monospaced font does tricks on us...

Regards,
Th.

**Comment by HeinrichAD** [comment]
If that's the case I will close this issue. Feel free to reopen it.
