### ISSUE TITLE
[feature] allow SVG to show in a frame together with the source

### ISSUE THREAD

**Issue by VladimirAlexiev** [plantuml/plantuml-server#335]
Currently `/uml` on the server shows the source, and a PNG below (or to the right) of it.
- And there are links to show PNG, SVG, ASCII Art.

This works fine for most diagrams, but there are some where the SVG looks or works differently from the PNG.
Most importantly, when using links and tooltips, these work only in SVG but not PNG.

So it would be very useful if there's an option to show **SVG** in a frame below (or to the right of) the source.
- Two radio-buttons "PNG vs SVG" also need to be added
- It would be great if someone with UX experience can figure out how to combine these radio-buttons with the existing links

**Comment by HeinrichAD** [comment]
It is already possible to chose what you want to see on the right side.
As an example please look into the documentation: <https://github.com/plantuml/plantuml-server/blob/master/docs/WebUI/settings.md#rendering-type>

Please keep in mind that the plantuml-server (this repository) and the PlantUML online service (http://www.plantuml.com) are **not** the same. The later on is closed source as far as I know.
