### ISSUE TITLE
Proxy service redirects instead of showing resource

### ISSUE THREAD

**Issue by Splines** [plantuml/plantuml-server#340]
### **What is the URL of the documentation?**

[Documentation: PlanUML > Plugins > HTTPServer > Proxy Service](https://plantuml.com/server) 

### **What can be improved?**

The "Proxy service" section states that an optional `fmt` parameter can be specified in the URL in order to return a specified format like `svg`, `png` etc. However, when modifying the provided example link by appending `&fmt=svg`, we still get redirected instead of retrieving the actual format directly.

https://www.plantuml.com/plantuml/proxy?src=https://raw.github.com/plantuml/plantuml-server/master/src/main/webapp/resource/test/test2diagrams.txt&fmt=svg

### **Additional context**

I've noticed this on one of my projects [documentation page](https://splines.github.io/dominion-cli/solid) where I made use of plantuml and your proxy server to directly embed SVG images. If you want to prevent this by redirecting instead (to reduce load on your server), I'd totally understand, but would love to also see this reflected in the documentation.

**Comment by arnaudroques** [comment]
> If you want to prevent this by redirecting instead (to reduce load on your server), I'd totally understand, but would love to also see this reflected in the documentation.

Sorry, we have some perf issue on the server and we broke this unintentionally.
We are going to restore the previous behavior.

Thanks for pointing this out!

**Comment by arnaudroques** [comment]
This should be fixed now.
Tell us if it's not working for you!

**Comment by Splines** [comment]
It's working yeah, thank you very much.
