### ISSUE TITLE
unicode error

### ISSUE THREAD

**Issue by ufo22940268** [plantuml/plantuml-server#35]
Can not correctly recognize chinese character 
![image](https://cloud.githubusercontent.com/assets/848704/24889909/6c5fb226-1e9f-11e7-95f3-d7f2e0dc3bc4.png)

But it works fine in online demo of official website. 

The server version i use is `201709`

**Comment by arnaudroques** [comment]
This might be releated with the default charset setting of your serveur.
Could you post the image generated by the following diagram:
```
@startuml
version
@enduml
```

Thanks

**Comment by ufo22940268** [comment]
![image](https://cloud.githubusercontent.com/assets/848704/24905040/1f687430-1ee5-11e7-95cc-6a603913cdd4.png)

**Comment by arnaudroques** [comment]
Charset seems to be ok (UTF-8)
Could you try the following example:
```
@startuml
alice -> bob : test <U+4E10>
@enduml
```
http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuKhCoKnELT2rKqZAJrAmKYX9BIvHi0dLDd4rDB3ZSaZDIm4g0W00
It would help to know if your issue is a font issue or not.

**Comment by ufo22940268** [comment]
![image](https://cloud.githubusercontent.com/assets/848704/24936199/cb0c7f92-1f59-11e7-9c41-76961c4e7921.png)

**Comment by arnaudroques** [comment]
Ok, it seems that no font supporting CJK character is deployed on your server.
You can double-check this with the special diagram:
```
@startuml
listfont
@enduml
```

or 

```
@startuml
listfont test <U+4E10>
@enduml
```
Those diagrams print all fonts available: in your case, there are probably no CJK fonts in this list.
You have to install such fonts on your server so that PlantUML could print chinese characters.
Does it help you ?

**Comment by ufo22940268** [comment]
thanks

**Comment by ufo22940268** [comment]
After i install chinese font, everything works fine! thanks.
