### ISSUE TITLE
Add fonts to docker image

### ISSUE THREAD

**Issue by jmatsushita** [plantuml/plantuml-server#43]
Hi there,

The list of fonts installed on the official docker image is:

![image](https://cloud.githubusercontent.com/assets/356097/25710857/ceda5770-30ed-11e7-8164-02afce3f346e.png)

It would be great to add a few!

Cheers,

Jun

**Comment by jtiai** [comment]
This would be great thing to be document how to add more fonts to image.

**Comment by roxspring** [comment]
Would be particularly awesome if I could use the official Docker image but mount a volume of .ttf files at e.g. `/fonts` to have those available in my diagrams.

**Comment by paddy-hack** [comment]
The Docker images contain the Chinese `fonts-wqy-zenhei` package.  While this seems to work for Japanese, I was wondering if there are more suitable font packages for a setup where I only(?) need English and Japanese.

**Comment by translucens** [comment]
You can use Google Noto Fonts with latest PlantUML image and PlantUML source like this:

```
@startuml
skinparam defaultFontName Noto Sans CJK JP Medium
@enduml
```

**Comment by paddy-hack** [comment]
@translucens Thanks!  I've gotten a few "complaints" about Chinese-looking kanji.  Some of there were just slightly off but other were either arcane or plain off.

I've now replaced `fonts-wqy-zenhei` with `fonts-noto-cjk` and with that `skinparam` addition everything looks fine!  Problem is, my PlantUML server has a fair number of users who may have who knows how many PlantUML diagrams all over the place.  I can't really tell them to go fix up their diagrams so I would like to make `fonts-noto-cjk` the server's default font, with a preference for Japanese.  Any ideas how to go about this?

I think I prefer convincing the container's JVM to use the fonts of my preference (via `fontconfig`?) but another option would be to use a configuration file for `plantuml-server`.  However, I have not much of a clue as to how to achieve either.  Suggestions very welcome.
