### ISSUE TITLE
Redirections with absolute urls

### ISSUE THREAD

**Issue by milipili** [plantuml/plantuml-server#49]
Hi,
In my current setup, Plantuml is working behind a proxy and is accessible via http://somewhere.local/plantuml.
However all redirections (from platnuml) fail since it seems it assumes that the root directory is `/`. So you can get something like `http://somewhere.local/uml/blabla` instead of `http://somewhere.local/plantuml/uml/blabla`

Example:
* Going to `http://somewhere.local/plantuml`
* Redirected to `http://somewhere.local/uml/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000`

via curl:
```
% curl -v -L http://somewhere.local/plantuml/
*   Trying 100.73.1.89...
* TCP_NODELAY set
* Connected to somewhere.local (100.73.1.89) port 80 (#0)
> GET /plantuml/ HTTP/1.1
> Host: somewhere.local
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 302 Found
< Server: nginx
< Date: Thu, 03 Aug 2017 04:27:14 GMT
< Transfer-Encoding: chunked
< Connection: keep-alive
< Location: http://somewhere.local/uml/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000
<
* Ignoring the response-body
* Connection #0 to host somewhere.local left intact
* Issue another request to this URL: 'http://somewhere.local/uml/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000'
* Found bundle for host somewhere.local: 0x7ffce7c0b590 [can pipeline]
* Re-using existing connection! (#0) with host somewhere.local
* Connected to somewhere.local (100.73.1.89) port 80 (#0)
> GET /uml/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000 HTTP/1.1
> Host: somewhere.local
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Server: nginx
< Date: Thu, 03 Aug 2017 04:27:14 GMT
< Content-Type: text/html
< Content-Length: 162
< Connection: keep-alive
< Vary: Accept-Encoding
<
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
* Connection #0 to host somewhere.local left intact
```

The nginx setup, if not good for some reasons:
```
upstream backend-plantuml {
    least_conn;
    server some-backend.local:80 weight=1;
}

location /plantuml/ {
    proxy_set_header HOST $host;
    proxy_connect_timeout 500ms; # approximate
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    rewrite ^/plantuml/(.*) /$1 break;
    proxy_pass http://backend-plantuml;
}
```

**Comment by arnaudroques** [comment]
>  So you can get something like http://somewhere.local/uml/blabla instead of http://somewhere.local/plantuml/uml/blabla

If you want to do this, the best option is to rename plantuml.war to root.war when installing it to your application server.

> rewrite ^/plantuml/(.*) /$1 break;

I am confused by this rule : it removes the /plantuml/ **before** sending the request to the plantuml server, and I've got the feeling that you want to do the other way.

I think you should try to make plantuml & nginx working together without url rewriting before going to something more complex

**Comment by milipili** [comment]
Hum sorry I forgot to mention that I was using the docker image for plantuml. Maybe that's not a good solution at all...
Well this docker image definitively lacks of options to be honest...

**Comment by milipili** [comment]
Using an additional nginx / container is definitively overkill in my humble opinion....
