### ISSUE TITLE
latest version

### ISSUE THREAD

**Issue by VladimirAlexiev** [plantuml/plantuml-server#51]
We wanted to install puml-server for integration to gitlab.
As per https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/administration/integration/plantuml.md, we did
`git clone https://github.com/plantuml/plantuml-server.git`
This built version 1.2017.14. 

But I bet the latest is 1.2017.15 from 
http://sourceforge.net/projects/plantuml/files/plantuml.war/download, as explained at http://plantuml.com/server.

If github doesn't have the latest version of plantuml-server, I believe it is actually harmful.

**Comment by VladimirAlexiev** [comment]
The bet above is wrong:
- our own: http://93.123.21.93:9080/plantuml/uml/IqpABoq10000 shows 1.2017.14, and was installed from http://sourceforge.net/projects/plantuml/files/plantuml.war/download
- "official": http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuKfCoYyjuN98pKi1yW00 shows 1.2017.16beta5.

When I test a diagram with colors, tooltips and icons, I see these problems of [our server](http://93.123.21.93:9080/plantuml/uml/dL9TRzem57tFhxZAwufAmbHL4OhKhcFJL4QrjayHYYx91JmSEx9DDnJrlyzsO8ICIjlo59_xTUuvTyrA0gfgiuEAgWKf7QmTL31LSDe_j255qkng2WAzOQ96XHKq0S1dYodEnEQ3v5B1WcEnwSBFelG_14laceBNJdt1KMlVvTPMhPJSYjAt6OzHcHzIRT8Kt7VFLcjpoxTqDhMkYNCqJ0gR_YGhDDAE2GmpdEnRSiDge9zOrNQV13wH8CMA2_ZoEFjwVtS1t-ucGT1o4RAa2BAiEPJ9POkzpkUUQ9Oj6V6o6_U0ZTkPnoRncIQnQnAq8mQ3T9-Ns4mgLzJDTc_NyK1hEfr5W1h2iLnyfy9SHca8NP4ijImRFx-B9gERwnISKJ15CSMIPhwYGIXKbNoCuzpY0nV8suYROulz86PtANCx2D4ae-5mE1fTHTUDgto8ypNgt7SEQsJ2CB62x8NfBN9mDEPXLuGdftwFzAMtfAL-ObghhEKVNmqdU_etnum3-VTHta4zSLlsWlOm87mWr2WCe2ZXSKrKXuqgbucFjiIyYaxuFJUdl3rkkubVUx5h5uroflCJl6T5_2zMlAbxywT91ojwSlVCE37ghws8_y-AiyetPrpuhVLP9qvTY8ykjFV_XkvDtuLV) compared to the ["official" server](http://www.plantuml.com/plantuml/uml/dLHTRzem57tFhxZAwufAmbHL2A6swzWqbL6jxLE4eajy0G_7ZcpJ3KNzxxKT685IQLkUx7E_pZt7ofMngEsw5D6ICm8gAxk1aiePQTD01TU5eEt5MDAaxAQYA38hBYlKM48T0Nnrc1PShZufeJJC11QhDlmaMJWGp54OYbvQzOL0OqAN6rUrq6ejMMWp63XolvHU3OVWlpk-MDeRiQQJgLL5Gg3bIhhqHrMYLMvCPBaLvEvAM5u1_SQoSllquGj9qhmuWsyFa-ztjsVmutOKHGqNgHWba6NrhapD6-nbEWr4ispEIR1sF00kxcRkcwGdcgI-ITICw7I6sxo-ooIse7Qsl_kEErhZyIG1D10FrEmd5VOy6SRG5ibHoxB1quTarBk-788t2iOenyXe4YfgX4AN_SzfcZkyumDv4_5pN74OnDqkB7U346s_r-rsUxsBvBBsbVTflaIJXyvnXLnQBXUGFNEpHW6UnZHkY_3erJyYVHuiQQWVcDOew_Yd5ztHblxrFcD7_cEIjz10t9KzetiO4DyJ6fGMK39uM19LSQtPl1-Y3R6WeXT-oyqhxnwtsoIiFTiqYoOvD_a1VcH5-YzMlAjx_TQadHL7SX-PSM3KNrkH_fyL9vMlJxZmH-kJJXowaEvTQDx_ExhNRrou8idSJ-iL)
- the UI looks differently. There is no "Switch layout", "View as PNG"
- View Map Data returns nothing
- Tooltips don't work
- Unicode chars are broken. This is likely a problem of what Unicode fonts are installed: a 5-char codepoint <U+1F3A8> doesn't work but a 4-char codepoint <U+260F> works
- there's an extra compartment at the bottom, despite `hide empty members`

So @arnaudroques, when can we expect the latest server version officially released?
Why 1.2017.15 is not released?

**Comment by arnaudroques** [comment]
> Why 1.2017.15 is not released?

A simple mistake : we've just released it as well as the .war file

> I see these problems of our server compared to the "official" server

Thanks for the feedback : reporting those evolutions to the GitHub repository will take some times : please be patient!

**Comment by VladimirAlexiev** [comment]
Also: Slack inlines images returned by your server, 
```
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Content-Type: image/png
Expires: Tue, 12 Sep 2017 17:51:16 GMT
Date: Thu, 07 Sep 2017 17:51:16 GMT
Last-Modified: Sun, 03 Sep 2017 10:53:00 GMT
Cache-Control: public, max-age=432000
ETag: "1a0QQ3e5woKoHr3kmSXOWIzS000"
X-PlantUML-Diagram-Description: (15 entities)
X-Powered-By: PlantUML Version 1.2017.16
X-Patreon: Support us on http://plantuml.com/patreon
X-Donate: http://plantuml.com/paypal
X-Quote: This bug is a feature as described by the marketing department.
X-PlantUML-Measure: 1/95/343
X-PlantUML-Diagram-Width: 788
X-PlantUML-Diagram-Height: 550
Content-Length: 34132
Server: PlantUML/0.6
```
But not those generated by our server. 
```
Server: Apache-Coyote/1.1
Expires: Tue, 12 Sep 2017 17:51:35 GMT
Date: Thu, 07 Sep 2017 17:51:36 GMT
Last-Modified: Sun, 03 Sep 2017 10:53:00 GMT
Cache-Control: public, max-age=432000
Etag: "1a0b7QuL62_tyBEgIEaiQgFKG00"
X-PlantUML-Diagram-Description: (6 entities)
X-Powered-By: PlantUML Version 1.2017.16
X-Patreon: Support us on http://plantuml.com/patreon
X-Donate: http://plantuml.com/paypal
Content-Type: image/png
Content-Length: 13904
```
I think we need to add the `Access-Control-Allow-Origin: *` header.

**Comment by VladimirAlexiev** [comment]
> Unicode chars are broken. a problem of the default encoding (UTF-8 on your server, ANSI-X3-1968 which means ASCII on ours)

According to https://stackoverflow.com/questions/1006276/what-is-the-default-encoding-of-the-jvm, this can be changed in several ways:
- set env var LC_ALL=en_US.UTF-8
- set env var JAVA_TOOLS_OPTIONS=-Dfile.encoding=UTF-8
- cmd-line option when starting java: -Dfile.encoding=UTF-8

Note: the cmd-line plantuml has this option
`java -jar plantuml.jar -charset UTF-8`

**Comment by PeterDaveHello** [comment]
Similar situation, the latest version on [GitHub release page](https://github.com/plantuml/plantuml-server/releases) is v1.2019.1 but the latest on [SourceForge](https://sourceforge.net/projects/plantuml/files/) is v1.2019.3

**Comment by HeinrichAD** [comment]
Let's sum it up.

- The ["official" server](http://www.plantuml.com/plantuml) uses not always the latest stable version. It also uses beta versions. [plantuml-server](https://github.com/plantuml/plantuml-server) is only _"released"_ with stable versions.
- The ["official" server](http://www.plantuml.com/plantuml) is **NOT** the same as [plantuml-server](https://github.com/plantuml/plantuml-server). The first is close source and could have different basic settings. The later one is open source. But both use the same core under the surface: [PlantUML](https://github.com/plantuml/plantuml).
- The `Access-Control-Allow-Origin: *` header as well as features like `View Map Data` has been added in the meantime.
