### ISSUE TITLE
enable PLANTUML_LIMIT_SIZE as Docker environment variable

### ISSUE THREAD

**Issue by bufferoverflow** [plantuml/plantuml-server#54]
Would be nice if  `PLANTUML_LIMIT_SIZE` could be used as Docker environment variable in the same way as on command line.

**Comment by Ducatel** [comment]
Hi, 
I did some test and it working without any update
```
docker run -ti --rm -p 8080:8080 -e PLANTUML_LIMIT_SIZE=4567 plantuml/plantuml-server:jetty
```

![image](https://user-images.githubusercontent.com/1184332/30848481-89ed171e-a29f-11e7-974f-757f0497c7b0.png)

As you can see, the value of `PLANTUML_LIMIT_SIZE` was correctly setted.

**Comment by bufferoverflow** [comment]
Thank you!
