### ISSUE TITLE
Use embedded Tomcat (or Jetty) to make an executable jar

### ISSUE THREAD

**Issue by svpace** [plantuml/plantuml-server#57]
Embedding a Tomcat or Jetty and making the package an "executable war" ala Spring Boot (https://docs.spring.io/spring-boot/docs/current/reference/html/deployment-install.html) would make a lot easier to deploy the plantuml server.

**Comment by morotti** [comment]
related to #91 

Once the plantuml war is published as part of the releases. You will be able to download the plantuml war, download the jetty-runner war https://www.eclipse.org/jetty/documentation/9.4.x/runner.html
Then run with ``java -jar jetty-runner.jar --path / plantuml.war``.
