### ISSUE TITLE
Docker Server doesn't support map

### ISSUE THREAD

**Issue by qjebbs** [plantuml/plantuml-server#58]
Hi, 

I start the container with `docker run -d -p 8080:8080 plantuml/plantuml-server:jetty`, get nothing from the following url:

<http://localhost:8080/map/SyfFKj2rKt3CoKnELR1IY8vEr4lEpusD1G00>

Thanks!

**Comment by arnaudroques** [comment]
Thanks for the report.
We've just pushed the correction https://github.com/plantuml/plantuml-server/commit/b9bb9c71c535398f2feff3367e85b53f8cbb46fe
The docker server should be updated automatically after this push. Tell us if it's not working.
Regards,

**Comment by qjebbs** [comment]
Seems still not work, blank page just like the past:

```
docker run -d -p 8080:8080 plantuml/plantuml-server
docker pull plantuml-server

```

**Comment by arnaudroques** [comment]
For some reason, only the tomcat version has been updated.
https://hub.docker.com/r/plantuml/plantuml-server/tags/
Could you try on tomcat to see if it's working there ? Thanks

**Comment by qjebbs** [comment]
hmm...Still blank with tomcat

```
docker run -d -p 8080:8080 plantuml/plantuml-server:tomcat
Unable to find image 'plantuml/plantuml-server:tomcat' locally
tomcat: Pulling from plantuml/plantuml-server
723254a2c089: Pull complete 
abe15a44e12f: Pull complete 
409a28e3cc3d: Pull complete 
a9511c68044a: Pull complete 
9d1b16e30bc8: Pull complete 
0fc5a09c9242: Pull complete 
d34976006493: Pull complete 
3b70003f0c10: Pull complete 
bc7887582e2e: Pull complete 
9571c6814491: Pull complete 
ce1daa3b30dd: Pull complete 
5fbdec45baef: Pull complete 
b15d8c524fe4: Pull complete 
d9bdf117a608: Pull complete 
54ce65996a61: Pull complete 
15b76cb27cee: Pull complete 
Digest: sha256:1214be523cc388ecde16a765a9e94c4e30c49b5671f5793c9a60f975d74ba9de
Status: Downloaded newer image for plantuml/plantuml-server:tomcat
615060dd6316b6fe135cc0506356e71c67281d2c1bbd3304bb050482363a0969
```

**Comment by Ducatel** [comment]
With jetty container I have that 
```
<map id="plantuml_map" name="plantuml_map">
<area shape="rect" id="id1" href="a.com" title="a.com" alt="" coords="38,50,78,65"/>
</map>
```

**Comment by qjebbs** [comment]
Yes, it works. Thank you!
Maybe the docker mirror I used not updated when I tested the new image.
