### ISSUE TITLE
Beta Gantt feature not available in docker server

### ISSUE THREAD

**Issue by nmDejamobile** [plantuml/plantuml-server#59]
Hi,

I encounter an error when trying to draw Gantt (beta, I know) diagrams even with the demo diagram code available on plantuml site.
```
@startgantt
[Prototype design] lasts 15 days
[Test prototype] lasts 10 days
@endgantt
```
Neither Image, txt or svg format works.
Image shows a square with only "plantuml diagram" text.
SVG and TXT format throw the following error : 

> Sorry, but things didn't work out as planned.
> 
> Fri Dec 01 12:19:01 UTC 2017
> Request that failed: /txt/SoWkIImgIK_CAodXYWueoY_9BwaiI5L8IItEJC-BLSX9B2ufLZ0qLKX9h2pcYWv9BIvHA82fWaiRGAGTKlDIm2O10000
> Status code: 500
> Exception: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
> 

Is it implemented in this docker release ?
Il use the latest image from docker hub.

> $ docker pull plantuml/plantuml-server:jetty
> jetty: Pulling from plantuml/plantuml-server
> Digest: sha256:2f630034b6875e08904e3d74e09a5ee25b88fd5afb16034031ef8e235d4b22ca
> Status: Image is up to date for plantuml/plantuml-server:jetty

Thanks.

**Comment by arnaudroques** [comment]
Try to use @startuml instead 

Envoyé depuis Yahoo Mail pour Android 
 
  Le ven., déc. 1, 2017 à 11:25, Nicolas MASSART<notifications@github.com> a écrit :   
Hi,

I encounter an error when trying to draw Gantt (beta, I know) diagrams even with the demo diagram code available on plantuml site.
@startgantt
[Prototype design] lasts 15 days
[Test prototype] lasts 10 days
@endgantt

Neither Image, txt or svg format works.
Image shows a square with only "plantuml diagram" text.
SVG and TXT format throw the following error :


Sorry, but things didn't work out as planned.

Fri Dec 01 12:19:01 UTC 2017
Request that failed: /txt/SoWkIImgIK_CAodXYWueoY_9BwaiI5L8IItEJC-BLSX9B2ufLZ0qLKX9h2pcYWv9BIvHA82fWaiRGAGTKlDIm2O10000
Status code: 500
Exception: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0


Is it implemented in this docker release ?
Il use the latest image from docker hub.


$ docker pull plantuml/plantuml-server:jetty
jetty: Pulling from plantuml/plantuml-server
Digest: sha256:2f630034b6875e08904e3d74e09a5ee25b88fd5afb16034031ef8e235d4b22ca
Status: Image is up to date for plantuml/plantuml-server:jetty


Thanks.
