### ISSUE TITLE
plantuml-stdlib is not included with this server

### ISSUE THREAD

**Issue by domaslasauskas** [plantuml/plantuml-server#60]
I've started server using docker

```
docker run -d -p 8080:8080 plantuml/plantuml-server:jetty
```

and tried to render example from [plantuml-stdlib](/plantuml/plantuml-stdlib) on my [local server](http://localhost:8080/uml/SoWkIImgAStDuLBCp4lEAKr9LR19B2_MJyxFpStFiqCJ3Ix9BqfCJzLtp4sioiyBDeOp22fCAatEJYs1KdPSN8w-Zb7-Vi766iN6yPbv9Qb5UOavcYYY1K1tvQKMwIY5fUQbv1Uf5oi46ojfSY6fLx3HLK0ev780gWDw1000): 

```
@startuml
!include <aws/common>
!include <aws/Storage/AmazonS3/AmazonS3>
!include <aws/Storage/AmazonS3/bucket/bucket>

AMAZONS3(s3_internal)
AMAZONS3(s3_partner,"Vendor's S3")
s3_internal <- s3_partner
@enduml
```

but got an error:

![image](https://user-images.githubusercontent.com/2464675/33672113-511aee4a-daa1-11e7-9b22-0734d2758d12.png)

---

It works correctly on [the official server](http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuLBCp4lEAKr9LR19B2_MJyxFpStFiqCJ3Ix9BqfCJzLtp4sioiyBDeOp22fCAatEJYs1KdPSN8w-Zb7-Vi766iN6yPbv9Qb5UOavcYYY1K1tvQKMwIY5fUQbv1Uf5oi46ojfSY6fLx3HLK0ev780gWDw1000).

**Comment by yewton** [comment]
I cannot reproduce that using version 1.2018.1 😕 
It might have been fixed 🤔  

![localhost_8080_uml_kypciyufjkbli4aibzpfpi_dps-pur944gqkoizaj4_ltyndhchf2pq6cmwgj2fdpaujwl9sn5oelevh_dx1nxh5nl6puimfhnc9epeeewm9hilvgkkwic6fuidvhuh52i76iffsieelr7gl40e1](https://user-images.githubusercontent.com/363938/35868138-08740dfa-0b9f-11e8-9cf6-5b828c1e28e2.png)

**Comment by domaslasauskas** [comment]
I can confirm that this now works on `PlantUML Server 20180129-2050 / version 1201801`
