### ISSUE TITLE
Issues while rendering images in Gitlab

### ISSUE THREAD

**Issue by davidcharles008** [plantuml/plantuml-server#63]
I am trying to integrate PlantUML server with gitlab following link https://docs.gitlab.com/ce/administration/integration/plantuml.html#plantuml-server. 

Images/diagrams are not getting rendered in gitlab comments or AsciiDoc or wiki pages. Could you please help me to check it.?
![snippet2](https://user-images.githubusercontent.com/26871536/34270253-8b5e6a2e-e6ad-11e7-9149-be14f081bb67.jpg)
![snippet1](https://user-images.githubusercontent.com/26871536/34270254-8b8c8bc0-e6ad-11e7-9167-4b1bedf5257e.jpg)

**Comment by arnaudroques** [comment]
Could you right-click on the three images (the one working, and the two other ones) to see the URL of those image and post them here ? Thanks

**Comment by joharohl** [comment]
We had the same issue. Gitlab does not work with the latest version. We built our own from v1.2017.19 that works ok though. Not exactly sure what is going on, but assuming the algorithm for compressing the urls changed?

**Comment by arnaudroques** [comment]
Well, the algorithm by itself has not changed. There has been some change through : there were an old Huffman decoder that was not used since ages, so we have remove it. I don't think that Gitlab was using it. But I may be wrong.

Could you post here some of those non-working URL so that we could investigate on the subject ?
Without them, there is nothing we can do.

Thanks!

**Comment by davidcharles008** [comment]
None of them are working like expected.

One which shows "Welcome to PlantUML" - `http://ulisotv10.xxxx.xxx-net.net:8080/plantuml/png/U9nLa3qEmZ0CXNUVml84I1sWucUgUWC6s2e62n8HAIrIuo9nUvmebCQBexpFpo-1DWYFClKULfirLbM3pY9TNht1gmb2A4yp062KEXadSqFYkxYtamzkAIfn87EefHP_eYRaW5ohOdmm2OZyMV4HvRy1KrNUM2aCzfIaUJW5MUY7h0yFP-7N8U4nTDDPrlCoz4v3Puph-SMUWvHvoZr7WfoXk3vHzcgrnL-4B-BZNcS0`


Other two are given below.
`http://ulisotv10.xxx.xxx-net.net:8080/plantuml/uml/png/U9npoazIqBLJSCp9J4vLi5B8ICt9oUU2y832Ja1PAmNtV0N7yiHABW0XJWoz`

`http://ulisotv10.xxxx.xxx-net.net:8080/plantuml/uml/png/U9nLa3qEmZ0CXNUVml84I1sWucUgUWC6s2e62n8HAIrIuo9nUvmebCQBexpFpo-1DWYFClKULfirLbM3pY9TNht1gmb2A4yp062KEXadSqFYkxYtamzkAIfn87EefHP_eYRaW5ohOdmm2OZyMV4HvRy1KrNUM2aCzfIaUJW5MUY7h0yFP-7N8U4nTDDPrlCoz4v3Puph-SMUWvHvoZr7WfoXk3vHzcgrnL-4B-BZNcS0`

**Comment by arnaudroques** [comment]
Thanks for the URLs.
So we confirm that those URLs have been created using Huffman encoding only, which is somehow strange.
Anyway, we are going to restore the Huffman decoder in the next official release.

In the mean time, here is a beta version of the jar library http://beta.plantuml.net/plantuml.jar and of the war file library http://beta.plantuml.net/plantuml.war that should work back with those URLs (note that it has not been widely tested...)

**Comment by jsirpoma** [comment]
See discussion in https://gitlab.com/gitlab-org/gitlab-ce/issues/40203. As suggested there, downgrading to 1.2017.14 in pom.xml allows images to be displayed correctly.

**Comment by smcgivern** [comment]
GitLab uses this library from @hsanson: https://github.com/hsanson/asciidoctor-plantuml

Perhaps they know more?

**Comment by davidcharles008** [comment]
I have tried both the options suggested. No luck.. :(  I get "Welcome to PlantUML" image as it was there earlier. 

```
Option 1 - using http://beta.plantuml.net/plantuml.war 
Option 2 - downgrading version to 1.2017.14 in pom.xml
```

**Comment by arnaudroques** [comment]
It may be a cache issue here : can you try with some other diagram ?

**Comment by hsanson** [comment]
Maybe not very helpful but this is the version I use in my gitlab installation:

```
PlantUML Server 20170518-0842 / version 1201713
```

The asciidoctor-plantuml gem is based 100% in the plantuml java source of the version above. If there has been changes to the way URLs are encoded then these must be added too to the gem. Not sure I can take time to add the changes to the gem now.

**Comment by davidcharles008** [comment]
@arnaudroques : Thanks, other diagrams are working now. Maybe downgrading the version helped. How to clear the cache .?

**Comment by arnaudroques** [comment]
To clear the cache, you can use Ctrl-F5 : I think the cache is on your browser side.

Note that we've just published version 1.2018.0 that fixes this rendering image issue. In the future, we will keep the Huffman decoder, even if we don't use it anymore.
Sorry about all this story !

**Comment by jsirpoma** [comment]
I can confirm that 1.2018.0 works again!

**Comment by davidcharles008** [comment]
I too confirm that issue is fixed in newer version. So this issue can be closed.
