### ISSUE TITLE
frontpage redirect

### ISSUE THREAD

**Issue by glensc** [plantuml/plantuml-server#64]
i've setup docker image which is behind haproxy, which itself is on https.

now if i access the service over https, it redirects to http url. it's apparently due haproxy connecting over http and plantuml not being able to understand that.

1. how to configure it to redirect to https url?

```
$ curl -i https://plantuml.example.net
HTTP/1.1 302 Found
Connection: close
Location: http://plantuml.example.net/uml/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000
Server: Jetty(9.4.6.v20170531)
```

**Comment by yewton** [comment]
According to [Jetty Docker image document](https://hub.docker.com/_/jetty/), you can try:

```
docker run --rm -p 8080:8080 plantuml/plantuml-server:jetty --module=http-forwarded
```

Or configure haproxy to redirect HTTP traffic to HTTPS.

**Comment by glensc** [comment]
thanks. seems working!
