### ISSUE TITLE
Error starting userland proxy: mkdir /port/tcp:0.0.0.0:8080:tcp:172.17.0.3:8080: input/output error

### ISSUE THREAD

**Issue by phillipzada** [plantuml/plantuml-server#65]
Hi,

Trying to startup a docker image and getting the following error. Any suggestions please?
I've tried both Tomcat and Jetty images.

```
docker run -d -p 8080:8080 plantuml/plantuml-server:jetty
```
```
d965e26e5a08c0664676b4b2aecb90e3573788b04f3e2996acf09c4fa1d68fa5
docker: Error response from daemon: driver failed programming external connectivity on endpoint practical_pare (8dc80a80905e476b95b0bc76aae7e398f343517c6f7858f40e1128b4d31d7796): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:8080:tcp:172.17.0.3:8080: input/output error.
```

**Comment by yewton** [comment]
Might be helpful: https://github.com/docker/compose/issues/3277

**Comment by ajkumar01** [comment]
i landed in this issue - as i ran into same error - while trying docker in windows with -p option.
For me the issue went away - when i started 'docker run ...'  from a  powershell that was run as 'administrator'.
This might help you as well.

**Comment by grinit10** [comment]
Restarting docker after building the image solved the problem for me.

**Comment by cmjchrisjones** [comment]
I just had a similar problem on , I ended up reinstalling the same version as what was already installed by going to *Docker settings -> general -> at the bottom click on switch to another version -> didn't change anything and hit install*, I let that run and finish and tried again and it worked. This was for a MySQL server image which was working then mysteriously stopped working, giving the error of:

**Error response from daemon: driver failed programming external connectivity on endpoint communityfitmysql2 (f354830893021c7724e3df92b7e8712f2a05747d6621e0577c2e95d701b506e3): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:3603:tcp:172.17.0.2:3306: input/output error.**

**Comment by fireflycons** [comment]
I get this problem if I RDP to a windows machine running docker desktop and try to start a container.
If I am on a console session at this machine, the container starts.

Is there something about RDP sessions that prevents containers from starting?

**Comment by navi-dev** [comment]
Its pretty bad to see how much time it takes to do start that. It took me 2 days to make it run.
