### ISSUE TITLE
Using with Nginx SSL termination proxy https -> http

### ISSUE THREAD

**Issue by 1am** [plantuml/plantuml-server#66]
Hi,

I'm trying to expose plantuml-server docker via Nginx with SSL enabled and while the cert works fine for server running on port 80 it doesn't for plantuml-server exposed on different port. 

The setup seems to be called "Nginx proxy with SSL termination" and is similar to what's shown on image in [https://www.digitalocean.com/community/tutorials/how-to-set-up-nginx-load-balancing-with-ssl-termination](https://www.digitalocean.com/community/tutorials/how-to-set-up-nginx-load-balancing-with-ssl-termination).

When I address the Nginx server via http it works ok but when i use https i get the following error:

```
:WARN:oejh.HttpParser:qtp1732398722-13: Illegal character 0x16 in state=START for buffer HeapByteBuffer@1c1b2884[p=1,l=201,c=8192,r=200]={\x16<<<\x03\x01\x00\xC4\x01\x00\x00\xC0\x03\x03\xAd\x06\x10F\x97=K...\x00\x08\n\n\x00\x1d\x00\x17\x00\x18JJ\x00\x01\x00>>>0\r\nETag: "3m0ukyV...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00
```

Is there some known way to fix this? Nginx configuration seems fine and host -> docker connection is normal HTTP so there should be no problems.

**Comment by yewton** [comment]
It seems that your SSL termination does not work properly so that Jetty is trying to parse HTTPS request as plain HTTP 🤔 
If your plantuml-server works properly using plain HTTP, I'm afraid that the problem is not on Jetty or plantuml-server but on speaking HTTP as a request, i.e. configuration of Nginx.

I've googled and found [this thread](https://stackoverflow.com/a/25625922/2142831), it might be helpful.

**Comment by HeinrichAD** [comment]
For documentary reasons: Some [examples](https://github.com/plantuml/plantuml-server/tree/master/examples) have been added concerning the usage of PlantUML Server. Among others, there are examples of how PlantUML Server can be set up behind a reverse proxy (Nginx).

- [Nginx simple reverse proxy example](https://github.com/plantuml/plantuml-server/blob/master/examples/nginx-simple)
- [Nginx reverse proxy example with defined location directive (different context path)](https://github.com/plantuml/plantuml-server/blob/master/examples/nginx-contextpath)
- [Kubernetes simple deployment](https://github.com/plantuml/plantuml-server/blob/master/examples/kubernetes-simple)
