### ISSUE TITLE
Support multiple images/new page functionality

### ISSUE THREAD

**Issue by danielvanmil** [plantuml/plantuml-server#7]
PlantUML supports the newpage mechanism that starts a new page/image for large schemas. Is it possible to generate a large image or separate images with the separate pages? At this moment only the image of the first page is returned.

I can fix this if I can find the time, but maybe it's already been taken care of?

Thanks in advance.

**Comment by qjebbs** [comment]
`plantuml.jar` has a para `-pipeimageindex`, I hope server could support similar para too.

**Comment by useltmann** [comment]
You can access the different pages by manipulating the url e.g.
```
@startuml
Bob -> Alice : hello
newpage
Alice -> Bob : hello
@enduml
```
produces
http://www.plantuml.com/plantuml/png/0/SoWkIImgAStDuNBAJrBGjLDmpCbCJbMmKiX8pSd9vyfBBIz8J4_b0ek2f86gu98EgNafG9q0
and 
http://www.plantuml.com/plantuml/png/1/SoWkIImgAStDuNBAJrBGjLDmpCbCJbMmKiX8pSd9vyfBBIz8J4_b0ek2f86gu98EgNafG9q0

Maybe thats an option

**Comment by qjebbs** [comment]
@useltmann  Many thanks!
