### ISSUE TITLE
How to pass arguments to the server when running mvn jetty:run?

### ISSUE THREAD

**Issue by evandrocoan** [plantuml/plantuml-server#70]
I tried this:
```
mvn jetty:run -Dexec.args="-enablestats -realtimestats -loopstats"
```
From http://www.logicbig.com/how-to/maven/mvn-java-exec-args/ but seems to do nothing.

**Comment by HeinrichAD** [comment]
For documentation purpose:

**Short answer**: The [command line arguments for PlantUML](https://plantuml.com/command-line) differ from the arguments for the PlantUML Server.

**More detailed answer**:

The [`plantuml.jar`](https://github.com/plantuml/plantuml) (core file) and the PlantUML Server are two different things. PlantUML Server provides web endpoints as well as a web frontend to use the underlying PlantUML Core. Therefore, both programs have different main entry points (in the source code) and that is why program arguments from `plantuml.jar` cannot be used/are not valid for the PlantUML Server.

To configure PlantUML, the core as well as the server, both support a number of environment variables, like e.g. `PLANTUML_STATS`, also documented in the official PlantUML documentation (see image below). Additionally, the `PLANTUML_PROPERTY_FILE` environment variable supports, starting with version `v1.2023.9`, to set PlantUML system properties (like over the Java command line using the `-Dpropertyname=value` syntax).

There exists a section _[How to set PlantUML options](https://github.com/plantuml/plantuml-server#how-to-set-plantuml-options)_ inside the README document.

----

![image](https://github.com/plantuml/plantuml-server/assets/5962361/b9b260cf-0315-4c31-916a-e46a3fbaa2f8)
Source: <https://plantuml.com/statistics-report>
