### ISSUE TITLE
support ascii math

### ISSUE THREAD

**Issue by nolange** [plantuml/plantuml-server#73]
Would be nice if AsciiMath is supported aswell.

http://plantuml.com/ascii-math
http://asciimath.org/

**Comment by HeinrichAD** [comment]
For documentation purpose:

Many years pasted and somewhere in between the support was added.


### Example 1
Source code taken from here: <https://plantuml.com/ascii-math>

```plantuml
@startuml
:<math>int_0^1f(x)dx</math>;
:<math>x^2+y_1+z_12^34</math>;
note right
Try also
<math>d/dxf(x)=lim_(h->0)(f(x+h)-f(x))/h</math>
<math>P(y|bb"x") or f(bb"x")+epsilon</math>
end note
@enduml
```

renders as:

![image](https://github.com/plantuml/plantuml-server/assets/5962361/88452689-ef59-467d-ae65-556f1cb06a82)


### Example 2

```plantuml
@startmath
sum_(i=1)^n i^3=((n(n+1))/2)^2
@endmath
```

![image](https://github.com/plantuml/plantuml-server/assets/5962361/b4130944-8503-4859-baca-132301ccc0f7)
