### ISSUE TITLE
Alpine-based image

### ISSUE THREAD

**Issue by wernight** [plantuml/plantuml-server#77]
I made a Linux Alpine image which seems to work just like the tomcat version but is a lot smaller (meaning it starts faster and takes less memory as well).

Here it's, and it should be easy to apply that to the Dockerfile.tomcat:

```
FROM tomcat:9-alpine

ENV LC_CTYPE en_US.UTF-8

RUN set -x \
    # Remove existing wars
 && rm -r /usr/local/tomcat/webapps/* \
    # Make dot executable available
 && apk add --no-cache curl graphviz ttf-dejavu \
    # Install PlantUML from http://plantuml.com/server
 && curl -Lo /usr/local/tomcat/webapps/plantuml.war http://sourceforge.net/projects/plantuml/files/plantuml.war/download \
    # Clean-up
 && apk del --purge curl
```

I can provide a PR, but it's just about using `tomcat:9-alpine` and then `apk add --no-cache` instead of `apt-get install -y`.

**Comment by HeinrichAD** [comment]
For documentation purpose:

Tomcat stopped offering an official images based on Alpine Linux 4 years ago. (See: [Docker Hub](https://hub.docker.com/_/tomcat/tags?page=1&name=alpine))

In theory, only an Alpine Linux image could be offered for the Jetty version of the server. There has even been a corresponding Dockerfile in the repository for some time. However, this is not officially supported or offered on Docker Hub. However, anyone is free to build an Alpine Linux image of PlantUML Server themselves. (However, you should not expect any help if you run into problems :sweat_smile:).
