### ISSUE TITLE
Access-Control-Allow-Origin hdr not included in HTTP Response when Image Map is requested

### ISSUE THREAD

**Issue by JulioCantarero** [plantuml/plantuml-server#78]
Based on the tests that I have done, when I get the URL "http://www.plantuml.com/plantuml/svg/ENCODED" or ".../png/...", the HTTP Response includes the CORS header "Access-Control-Allow-Origin *"
But when I try to fetch the "http://www.plantuml.com/plantuml/map/ENCODED", the HTTP response does NOT include this header "Access-Control-Allow-Origin" and the <map> information cannot be properly used by the browser.

**Comment by KenichiNagayasu** [comment]
I also have the same problem.

**Comment by arnaudroques** [comment]
Thanks for the report : this should be ok now.
Tell us if it's not working for you.
