### ISSUE TITLE
Using a different context path than root

### ISSUE THREAD

**Issue by simiolabs** [plantuml/plantuml-server#80]
Hello, I was trying to run the server on a different path than root, but since the the .war file was named ROOT.war it was impossible for me. I have changed this so now is possible to do it at build time like this:

docker image build --build-arg context_path=name_of_dot_war_file -t plantuml-server .

This is was my solution:

+ ARG context_path=ROOT
+
   RUN rm -rf /usr/local/tomcat/webapps/ROOT
-  COPY --from=builder /app/target/plantuml.war /usr/local/tomcat/webapps/ROOT.war+
+ COPY --from=builder /app/target/plantuml.war /usr/local/tomcat/webapps/${context_path}.war

This is obiviously not the best solution since I can't run the server on for example /my/context/path, just in /my_context_path

I think that this was supported before https://github.com/plantuml/plantuml-server/commit/d7a8a7e69831cab86a82bfb6deaaf0358d86d5b0

Thank you for your help!

**Comment by HeinrichAD** [comment]
For documentation purpose:

It is possible to change the base URL/context path with the environment variable `BASE_URL`.

There is a _[Change base URL](https://github.com/plantuml/plantuml-server#change-base-url)_ section in the REAMDE file.
