### ISSUE TITLE
Add a couple of rest calls to support a more interactive editor..?

### ISSUE THREAD

**Issue by ryankenney** [plantuml/plantuml-server#9]
I'm getting a ton of use out of plantuml these days. Having content embedded in the url is awesome!

I was messing around with a little cleaner online editor, and I ran into the issue of a couple of rest calls that seem to be missing, and would be helpful:
- Decode the diagram and return it as text
- Accept a diagram content and return it as a url (maybe I should just do encoding in JS?)

Anywho, if I get more time and interest down the line, I might flush these out more on the Java side. Thanks.

**Comment by ftomassetti** [comment]
Do we have any progress on this? What is the state of the plantuml grammar for CodeMirror?

**Comment by maximesinclair** [comment]
No progress at the moment, the plantuml grammar for CodeMirror is still a blank page. If you can help, do not hesitate, it will be apppreciated.

**Comment by ftomassetti** [comment]
I have started and now I have support for the Activity Diagrams (I am just not yet supporting the skin params). I am working on the CodeMirror mode for PlantUML in a separate project (just to contain the minimal example). It is available here: https://github.com/ftomassetti/codemirror_plantuml

As soon as I have finished the basic support (I am using all the examples from [planttext](http://www.planttext.com/)) I will ask help for preparing a PR.

**Comment by ftomassetti** [comment]
I start writing the tests to cover all the examples about the activity diagram. Planning to support all the examples on planttext, writing tests for them and then ask feedback.

**Comment by maximesinclair** [comment]
Nice to read this. I will try to have a look at your repo this week.

**Comment by ftomassetti** [comment]
I created an initial Pull Request for collecting feedback (see #17). Thanks!
